// Code generated by rclgo-gen. DO NOT EDIT.

package turtlesim_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <turtlesim/srv/set_pen.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("turtlesim/SetPen_Response", SetPen_ResponseTypeSupport)
	typemap.RegisterMessage("turtlesim/srv/SetPen_Response", SetPen_ResponseTypeSupport)
}

type SetPen_Response struct {
}

// NewSetPen_Response creates a new SetPen_Response with default values.
func NewSetPen_Response() *SetPen_Response {
	self := SetPen_Response{}
	self.SetDefaults()
	return &self
}

func (t *SetPen_Response) Clone() *SetPen_Response {
	c := &SetPen_Response{}
	return c
}

func (t *SetPen_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetPen_Response) SetDefaults() {
}

func (t *SetPen_Response) GetTypeSupport() types.MessageTypeSupport {
	return SetPen_ResponseTypeSupport
}

// SetPen_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetPen_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewSetPen_ResponsePublisher creates and returns a new publisher for the
// SetPen_Response
func NewSetPen_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetPen_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetPen_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetPen_ResponsePublisher{pub}, nil
}

func (p *SetPen_ResponsePublisher) Publish(msg *SetPen_Response) error {
	return p.Publisher.Publish(msg)
}

// SetPen_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetPen_ResponseSubscription struct {
	*rclgo.Subscription
}

// SetPen_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SetPen_ResponseSubscription.
type SetPen_ResponseSubscriptionCallback func(msg *SetPen_Response, info *rclgo.MessageInfo, err error)

// NewSetPen_ResponseSubscription creates and returns a new subscription for the
// SetPen_Response
func NewSetPen_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetPen_ResponseSubscriptionCallback) (*SetPen_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetPen_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetPen_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetPen_ResponseSubscription{sub}, nil
}

func (s *SetPen_ResponseSubscription) TakeMessage(out *SetPen_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetPen_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetPen_ResponseSlice(dst, src []SetPen_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetPen_ResponseTypeSupport types.MessageTypeSupport = _SetPen_ResponseTypeSupport{}

type _SetPen_ResponseTypeSupport struct{}

func (t _SetPen_ResponseTypeSupport) New() types.Message {
	return NewSetPen_Response()
}

func (t _SetPen_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.turtlesim__srv__SetPen_Response
	return (unsafe.Pointer)(C.turtlesim__srv__SetPen_Response__create())
}

func (t _SetPen_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.turtlesim__srv__SetPen_Response__destroy((*C.turtlesim__srv__SetPen_Response)(pointer_to_free))
}

func (t _SetPen_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _SetPen_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _SetPen_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__turtlesim__srv__SetPen_Response())
}

type CSetPen_Response = C.turtlesim__srv__SetPen_Response
type CSetPen_Response__Sequence = C.turtlesim__srv__SetPen_Response__Sequence

func SetPen_Response__Sequence_to_Go(goSlice *[]SetPen_Response, cSlice CSetPen_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetPen_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetPen_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetPen_Response__Sequence_to_C(cSlice *CSetPen_Response__Sequence, goSlice []SetPen_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.turtlesim__srv__SetPen_Response)(C.malloc(C.sizeof_struct_turtlesim__srv__SetPen_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetPen_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetPen_Response__Array_to_Go(goSlice []SetPen_Response, cSlice []CSetPen_Response) {
	for i := 0; i < len(cSlice); i++ {
		SetPen_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetPen_Response__Array_to_C(cSlice []CSetPen_Response, goSlice []SetPen_Response) {
	for i := 0; i < len(goSlice); i++ {
		SetPen_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
