// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	std_msgs_msg "test/msgs/std_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/msg/param.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/Param", ParamTypeSupport)
	typemap.RegisterMessage("mavros_msgs/msg/Param", ParamTypeSupport)
}

type Param struct {
	Header std_msgs_msg.Header `yaml:"header"`
	ParamId string `yaml:"param_id"`
	Value ParamValue `yaml:"value"`
	ParamIndex uint16 `yaml:"param_index"`
	ParamCount uint16 `yaml:"param_count"`
}

// NewParam creates a new Param with default values.
func NewParam() *Param {
	self := Param{}
	self.SetDefaults()
	return &self
}

func (t *Param) Clone() *Param {
	c := &Param{}
	c.Header = *t.Header.Clone()
	c.ParamId = t.ParamId
	c.Value = *t.Value.Clone()
	c.ParamIndex = t.ParamIndex
	c.ParamCount = t.ParamCount
	return c
}

func (t *Param) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Param) SetDefaults() {
	t.Header.SetDefaults()
	t.ParamId = ""
	t.Value.SetDefaults()
	t.ParamIndex = 0
	t.ParamCount = 0
}

func (t *Param) GetTypeSupport() types.MessageTypeSupport {
	return ParamTypeSupport
}

// ParamPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ParamPublisher struct {
	*rclgo.Publisher
}

// NewParamPublisher creates and returns a new publisher for the
// Param
func NewParamPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ParamPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ParamTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ParamPublisher{pub}, nil
}

func (p *ParamPublisher) Publish(msg *Param) error {
	return p.Publisher.Publish(msg)
}

// ParamSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ParamSubscription struct {
	*rclgo.Subscription
}

// ParamSubscriptionCallback type is used to provide a subscription
// handler function for a ParamSubscription.
type ParamSubscriptionCallback func(msg *Param, info *rclgo.MessageInfo, err error)

// NewParamSubscription creates and returns a new subscription for the
// Param
func NewParamSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ParamSubscriptionCallback) (*ParamSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Param
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ParamTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ParamSubscription{sub}, nil
}

func (s *ParamSubscription) TakeMessage(out *Param) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneParamSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneParamSlice(dst, src []Param) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ParamTypeSupport types.MessageTypeSupport = _ParamTypeSupport{}

type _ParamTypeSupport struct{}

func (t _ParamTypeSupport) New() types.Message {
	return NewParam()
}

func (t _ParamTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__msg__Param
	return (unsafe.Pointer)(C.mavros_msgs__msg__Param__create())
}

func (t _ParamTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__msg__Param__destroy((*C.mavros_msgs__msg__Param)(pointer_to_free))
}

func (t _ParamTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Param)
	mem := (*C.mavros_msgs__msg__Param)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.param_id), m.ParamId)
	ParamValueTypeSupport.AsCStruct(unsafe.Pointer(&mem.value), &m.Value)
	mem.param_index = C.uint16_t(m.ParamIndex)
	mem.param_count = C.uint16_t(m.ParamCount)
}

func (t _ParamTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Param)
	mem := (*C.mavros_msgs__msg__Param)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	primitives.StringAsGoStruct(&m.ParamId, unsafe.Pointer(&mem.param_id))
	ParamValueTypeSupport.AsGoStruct(&m.Value, unsafe.Pointer(&mem.value))
	m.ParamIndex = uint16(mem.param_index)
	m.ParamCount = uint16(mem.param_count)
}

func (t _ParamTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__msg__Param())
}

type CParam = C.mavros_msgs__msg__Param
type CParam__Sequence = C.mavros_msgs__msg__Param__Sequence

func Param__Sequence_to_Go(goSlice *[]Param, cSlice CParam__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Param, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ParamTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Param__Sequence_to_C(cSlice *CParam__Sequence, goSlice []Param) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__msg__Param)(C.malloc(C.sizeof_struct_mavros_msgs__msg__Param * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ParamTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Param__Array_to_Go(goSlice []Param, cSlice []CParam) {
	for i := 0; i < len(cSlice); i++ {
		ParamTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Param__Array_to_C(cSlice []CParam, goSlice []Param) {
	for i := 0; i < len(goSlice); i++ {
		ParamTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
