// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/command_long.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/CommandLong_Request", CommandLong_RequestTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/CommandLong_Request", CommandLong_RequestTypeSupport)
}

type CommandLong_Request struct {
	Broadcast bool `yaml:"broadcast"`// send this command in broadcast mode
	Command uint16 `yaml:"command"`
	Confirmation uint8 `yaml:"confirmation"`
	Param1 float32 `yaml:"param1"`
	Param2 float32 `yaml:"param2"`
	Param3 float32 `yaml:"param3"`
	Param4 float32 `yaml:"param4"`
	Param5 float32 `yaml:"param5"`// x_lat
	Param6 float32 `yaml:"param6"`// y_lon
	Param7 float32 `yaml:"param7"`// z_alt
}

// NewCommandLong_Request creates a new CommandLong_Request with default values.
func NewCommandLong_Request() *CommandLong_Request {
	self := CommandLong_Request{}
	self.SetDefaults()
	return &self
}

func (t *CommandLong_Request) Clone() *CommandLong_Request {
	c := &CommandLong_Request{}
	c.Broadcast = t.Broadcast
	c.Command = t.Command
	c.Confirmation = t.Confirmation
	c.Param1 = t.Param1
	c.Param2 = t.Param2
	c.Param3 = t.Param3
	c.Param4 = t.Param4
	c.Param5 = t.Param5
	c.Param6 = t.Param6
	c.Param7 = t.Param7
	return c
}

func (t *CommandLong_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *CommandLong_Request) SetDefaults() {
	t.Broadcast = false
	t.Command = 0
	t.Confirmation = 0
	t.Param1 = 0
	t.Param2 = 0
	t.Param3 = 0
	t.Param4 = 0
	t.Param5 = 0
	t.Param6 = 0
	t.Param7 = 0
}

func (t *CommandLong_Request) GetTypeSupport() types.MessageTypeSupport {
	return CommandLong_RequestTypeSupport
}

// CommandLong_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type CommandLong_RequestPublisher struct {
	*rclgo.Publisher
}

// NewCommandLong_RequestPublisher creates and returns a new publisher for the
// CommandLong_Request
func NewCommandLong_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*CommandLong_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, CommandLong_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &CommandLong_RequestPublisher{pub}, nil
}

func (p *CommandLong_RequestPublisher) Publish(msg *CommandLong_Request) error {
	return p.Publisher.Publish(msg)
}

// CommandLong_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type CommandLong_RequestSubscription struct {
	*rclgo.Subscription
}

// CommandLong_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a CommandLong_RequestSubscription.
type CommandLong_RequestSubscriptionCallback func(msg *CommandLong_Request, info *rclgo.MessageInfo, err error)

// NewCommandLong_RequestSubscription creates and returns a new subscription for the
// CommandLong_Request
func NewCommandLong_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback CommandLong_RequestSubscriptionCallback) (*CommandLong_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg CommandLong_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, CommandLong_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &CommandLong_RequestSubscription{sub}, nil
}

func (s *CommandLong_RequestSubscription) TakeMessage(out *CommandLong_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneCommandLong_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneCommandLong_RequestSlice(dst, src []CommandLong_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var CommandLong_RequestTypeSupport types.MessageTypeSupport = _CommandLong_RequestTypeSupport{}

type _CommandLong_RequestTypeSupport struct{}

func (t _CommandLong_RequestTypeSupport) New() types.Message {
	return NewCommandLong_Request()
}

func (t _CommandLong_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__CommandLong_Request
	return (unsafe.Pointer)(C.mavros_msgs__srv__CommandLong_Request__create())
}

func (t _CommandLong_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__CommandLong_Request__destroy((*C.mavros_msgs__srv__CommandLong_Request)(pointer_to_free))
}

func (t _CommandLong_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*CommandLong_Request)
	mem := (*C.mavros_msgs__srv__CommandLong_Request)(dst)
	mem.broadcast = C.bool(m.Broadcast)
	mem.command = C.uint16_t(m.Command)
	mem.confirmation = C.uint8_t(m.Confirmation)
	mem.param1 = C.float(m.Param1)
	mem.param2 = C.float(m.Param2)
	mem.param3 = C.float(m.Param3)
	mem.param4 = C.float(m.Param4)
	mem.param5 = C.float(m.Param5)
	mem.param6 = C.float(m.Param6)
	mem.param7 = C.float(m.Param7)
}

func (t _CommandLong_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*CommandLong_Request)
	mem := (*C.mavros_msgs__srv__CommandLong_Request)(ros2_message_buffer)
	m.Broadcast = bool(mem.broadcast)
	m.Command = uint16(mem.command)
	m.Confirmation = uint8(mem.confirmation)
	m.Param1 = float32(mem.param1)
	m.Param2 = float32(mem.param2)
	m.Param3 = float32(mem.param3)
	m.Param4 = float32(mem.param4)
	m.Param5 = float32(mem.param5)
	m.Param6 = float32(mem.param6)
	m.Param7 = float32(mem.param7)
}

func (t _CommandLong_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__CommandLong_Request())
}

type CCommandLong_Request = C.mavros_msgs__srv__CommandLong_Request
type CCommandLong_Request__Sequence = C.mavros_msgs__srv__CommandLong_Request__Sequence

func CommandLong_Request__Sequence_to_Go(goSlice *[]CommandLong_Request, cSlice CCommandLong_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]CommandLong_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		CommandLong_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func CommandLong_Request__Sequence_to_C(cSlice *CCommandLong_Request__Sequence, goSlice []CommandLong_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__CommandLong_Request)(C.malloc(C.sizeof_struct_mavros_msgs__srv__CommandLong_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		CommandLong_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func CommandLong_Request__Array_to_Go(goSlice []CommandLong_Request, cSlice []CCommandLong_Request) {
	for i := 0; i < len(cSlice); i++ {
		CommandLong_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func CommandLong_Request__Array_to_C(cSlice []CCommandLong_Request, goSlice []CommandLong_Request) {
	for i := 0; i < len(goSlice); i++ {
		CommandLong_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
