// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/command_tol_local.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/CommandTOLLocal_Response", CommandTOLLocal_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/CommandTOLLocal_Response", CommandTOLLocal_ResponseTypeSupport)
}

type CommandTOLLocal_Response struct {
	Success bool `yaml:"success"`
	Result uint8 `yaml:"result"`
}

// NewCommandTOLLocal_Response creates a new CommandTOLLocal_Response with default values.
func NewCommandTOLLocal_Response() *CommandTOLLocal_Response {
	self := CommandTOLLocal_Response{}
	self.SetDefaults()
	return &self
}

func (t *CommandTOLLocal_Response) Clone() *CommandTOLLocal_Response {
	c := &CommandTOLLocal_Response{}
	c.Success = t.Success
	c.Result = t.Result
	return c
}

func (t *CommandTOLLocal_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *CommandTOLLocal_Response) SetDefaults() {
	t.Success = false
	t.Result = 0
}

func (t *CommandTOLLocal_Response) GetTypeSupport() types.MessageTypeSupport {
	return CommandTOLLocal_ResponseTypeSupport
}

// CommandTOLLocal_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type CommandTOLLocal_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewCommandTOLLocal_ResponsePublisher creates and returns a new publisher for the
// CommandTOLLocal_Response
func NewCommandTOLLocal_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*CommandTOLLocal_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, CommandTOLLocal_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &CommandTOLLocal_ResponsePublisher{pub}, nil
}

func (p *CommandTOLLocal_ResponsePublisher) Publish(msg *CommandTOLLocal_Response) error {
	return p.Publisher.Publish(msg)
}

// CommandTOLLocal_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type CommandTOLLocal_ResponseSubscription struct {
	*rclgo.Subscription
}

// CommandTOLLocal_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a CommandTOLLocal_ResponseSubscription.
type CommandTOLLocal_ResponseSubscriptionCallback func(msg *CommandTOLLocal_Response, info *rclgo.MessageInfo, err error)

// NewCommandTOLLocal_ResponseSubscription creates and returns a new subscription for the
// CommandTOLLocal_Response
func NewCommandTOLLocal_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback CommandTOLLocal_ResponseSubscriptionCallback) (*CommandTOLLocal_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg CommandTOLLocal_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, CommandTOLLocal_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &CommandTOLLocal_ResponseSubscription{sub}, nil
}

func (s *CommandTOLLocal_ResponseSubscription) TakeMessage(out *CommandTOLLocal_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneCommandTOLLocal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneCommandTOLLocal_ResponseSlice(dst, src []CommandTOLLocal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var CommandTOLLocal_ResponseTypeSupport types.MessageTypeSupport = _CommandTOLLocal_ResponseTypeSupport{}

type _CommandTOLLocal_ResponseTypeSupport struct{}

func (t _CommandTOLLocal_ResponseTypeSupport) New() types.Message {
	return NewCommandTOLLocal_Response()
}

func (t _CommandTOLLocal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__CommandTOLLocal_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__CommandTOLLocal_Response__create())
}

func (t _CommandTOLLocal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__CommandTOLLocal_Response__destroy((*C.mavros_msgs__srv__CommandTOLLocal_Response)(pointer_to_free))
}

func (t _CommandTOLLocal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*CommandTOLLocal_Response)
	mem := (*C.mavros_msgs__srv__CommandTOLLocal_Response)(dst)
	mem.success = C.bool(m.Success)
	mem.result = C.uint8_t(m.Result)
}

func (t _CommandTOLLocal_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*CommandTOLLocal_Response)
	mem := (*C.mavros_msgs__srv__CommandTOLLocal_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	m.Result = uint8(mem.result)
}

func (t _CommandTOLLocal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__CommandTOLLocal_Response())
}

type CCommandTOLLocal_Response = C.mavros_msgs__srv__CommandTOLLocal_Response
type CCommandTOLLocal_Response__Sequence = C.mavros_msgs__srv__CommandTOLLocal_Response__Sequence

func CommandTOLLocal_Response__Sequence_to_Go(goSlice *[]CommandTOLLocal_Response, cSlice CCommandTOLLocal_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]CommandTOLLocal_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		CommandTOLLocal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func CommandTOLLocal_Response__Sequence_to_C(cSlice *CCommandTOLLocal_Response__Sequence, goSlice []CommandTOLLocal_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__CommandTOLLocal_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__CommandTOLLocal_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		CommandTOLLocal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func CommandTOLLocal_Response__Array_to_Go(goSlice []CommandTOLLocal_Response, cSlice []CCommandTOLLocal_Response) {
	for i := 0; i < len(cSlice); i++ {
		CommandTOLLocal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func CommandTOLLocal_Response__Array_to_C(cSlice []CCommandTOLLocal_Response, goSlice []CommandTOLLocal_Response) {
	for i := 0; i < len(goSlice); i++ {
		CommandTOLLocal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
