// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <mavros_msgs/srv/endpoint_del.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("mavros_msgs/EndpointDel", EndpointDelTypeSupport)
	typemap.RegisterService("mavros_msgs/srv/EndpointDel", EndpointDelTypeSupport)
}

type _EndpointDelTypeSupport struct {}

func (s _EndpointDelTypeSupport) Request() types.MessageTypeSupport {
	return EndpointDel_RequestTypeSupport
}

func (s _EndpointDelTypeSupport) Response() types.MessageTypeSupport {
	return EndpointDel_ResponseTypeSupport
}

func (s _EndpointDelTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__mavros_msgs__srv__EndpointDel())
}

// Modifying this variable is undefined behavior.
var EndpointDelTypeSupport types.ServiceTypeSupport = _EndpointDelTypeSupport{}

// EndpointDelClient wraps rclgo.Client to provide type safe helper
// functions
type EndpointDelClient struct {
	*rclgo.Client
}

// NewEndpointDelClient creates and returns a new client for the
// EndpointDel
func NewEndpointDelClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*EndpointDelClient, error) {
	client, err := node.NewClient(serviceName, EndpointDelTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &EndpointDelClient{client}, nil
}

func (s *EndpointDelClient) Send(ctx context.Context, req *EndpointDel_Request) (*EndpointDel_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*EndpointDel_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type EndpointDelServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s EndpointDelServiceResponseSender) SendResponse(resp *EndpointDel_Response) error {
	return s.sender.SendResponse(resp)
}

type EndpointDelServiceRequestHandler func(*rclgo.ServiceInfo, *EndpointDel_Request, EndpointDelServiceResponseSender)

// EndpointDelService wraps rclgo.Service to provide type safe helper
// functions
type EndpointDelService struct {
	*rclgo.Service
}

// NewEndpointDelService creates and returns a new service for the
// EndpointDel
func NewEndpointDelService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler EndpointDelServiceRequestHandler) (*EndpointDelService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*EndpointDel_Request)
		responseSender := EndpointDelServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, EndpointDelTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &EndpointDelService{service}, nil
}