// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/file_checksum.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/FileChecksum_Request", FileChecksum_RequestTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/FileChecksum_Request", FileChecksum_RequestTypeSupport)
}

type FileChecksum_Request struct {
	FilePath string `yaml:"file_path"`
}

// NewFileChecksum_Request creates a new FileChecksum_Request with default values.
func NewFileChecksum_Request() *FileChecksum_Request {
	self := FileChecksum_Request{}
	self.SetDefaults()
	return &self
}

func (t *FileChecksum_Request) Clone() *FileChecksum_Request {
	c := &FileChecksum_Request{}
	c.FilePath = t.FilePath
	return c
}

func (t *FileChecksum_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *FileChecksum_Request) SetDefaults() {
	t.FilePath = ""
}

func (t *FileChecksum_Request) GetTypeSupport() types.MessageTypeSupport {
	return FileChecksum_RequestTypeSupport
}

// FileChecksum_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type FileChecksum_RequestPublisher struct {
	*rclgo.Publisher
}

// NewFileChecksum_RequestPublisher creates and returns a new publisher for the
// FileChecksum_Request
func NewFileChecksum_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*FileChecksum_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, FileChecksum_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileChecksum_RequestPublisher{pub}, nil
}

func (p *FileChecksum_RequestPublisher) Publish(msg *FileChecksum_Request) error {
	return p.Publisher.Publish(msg)
}

// FileChecksum_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type FileChecksum_RequestSubscription struct {
	*rclgo.Subscription
}

// FileChecksum_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a FileChecksum_RequestSubscription.
type FileChecksum_RequestSubscriptionCallback func(msg *FileChecksum_Request, info *rclgo.MessageInfo, err error)

// NewFileChecksum_RequestSubscription creates and returns a new subscription for the
// FileChecksum_Request
func NewFileChecksum_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback FileChecksum_RequestSubscriptionCallback) (*FileChecksum_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg FileChecksum_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, FileChecksum_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FileChecksum_RequestSubscription{sub}, nil
}

func (s *FileChecksum_RequestSubscription) TakeMessage(out *FileChecksum_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFileChecksum_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFileChecksum_RequestSlice(dst, src []FileChecksum_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FileChecksum_RequestTypeSupport types.MessageTypeSupport = _FileChecksum_RequestTypeSupport{}

type _FileChecksum_RequestTypeSupport struct{}

func (t _FileChecksum_RequestTypeSupport) New() types.Message {
	return NewFileChecksum_Request()
}

func (t _FileChecksum_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__FileChecksum_Request
	return (unsafe.Pointer)(C.mavros_msgs__srv__FileChecksum_Request__create())
}

func (t _FileChecksum_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__FileChecksum_Request__destroy((*C.mavros_msgs__srv__FileChecksum_Request)(pointer_to_free))
}

func (t _FileChecksum_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FileChecksum_Request)
	mem := (*C.mavros_msgs__srv__FileChecksum_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.file_path), m.FilePath)
}

func (t _FileChecksum_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FileChecksum_Request)
	mem := (*C.mavros_msgs__srv__FileChecksum_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.FilePath, unsafe.Pointer(&mem.file_path))
}

func (t _FileChecksum_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__FileChecksum_Request())
}

type CFileChecksum_Request = C.mavros_msgs__srv__FileChecksum_Request
type CFileChecksum_Request__Sequence = C.mavros_msgs__srv__FileChecksum_Request__Sequence

func FileChecksum_Request__Sequence_to_Go(goSlice *[]FileChecksum_Request, cSlice CFileChecksum_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FileChecksum_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FileChecksum_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func FileChecksum_Request__Sequence_to_C(cSlice *CFileChecksum_Request__Sequence, goSlice []FileChecksum_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__FileChecksum_Request)(C.malloc(C.sizeof_struct_mavros_msgs__srv__FileChecksum_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FileChecksum_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func FileChecksum_Request__Array_to_Go(goSlice []FileChecksum_Request, cSlice []CFileChecksum_Request) {
	for i := 0; i < len(cSlice); i++ {
		FileChecksum_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FileChecksum_Request__Array_to_C(cSlice []CFileChecksum_Request, goSlice []FileChecksum_Request) {
	for i := 0; i < len(goSlice); i++ {
		FileChecksum_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
