// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <mavros_msgs/srv/file_remove_dir.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("mavros_msgs/FileRemoveDir", FileRemoveDirTypeSupport)
	typemap.RegisterService("mavros_msgs/srv/FileRemoveDir", FileRemoveDirTypeSupport)
}

type _FileRemoveDirTypeSupport struct {}

func (s _FileRemoveDirTypeSupport) Request() types.MessageTypeSupport {
	return FileRemoveDir_RequestTypeSupport
}

func (s _FileRemoveDirTypeSupport) Response() types.MessageTypeSupport {
	return FileRemoveDir_ResponseTypeSupport
}

func (s _FileRemoveDirTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__mavros_msgs__srv__FileRemoveDir())
}

// Modifying this variable is undefined behavior.
var FileRemoveDirTypeSupport types.ServiceTypeSupport = _FileRemoveDirTypeSupport{}

// FileRemoveDirClient wraps rclgo.Client to provide type safe helper
// functions
type FileRemoveDirClient struct {
	*rclgo.Client
}

// NewFileRemoveDirClient creates and returns a new client for the
// FileRemoveDir
func NewFileRemoveDirClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*FileRemoveDirClient, error) {
	client, err := node.NewClient(serviceName, FileRemoveDirTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileRemoveDirClient{client}, nil
}

func (s *FileRemoveDirClient) Send(ctx context.Context, req *FileRemoveDir_Request) (*FileRemoveDir_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FileRemoveDir_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FileRemoveDirServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s FileRemoveDirServiceResponseSender) SendResponse(resp *FileRemoveDir_Response) error {
	return s.sender.SendResponse(resp)
}

type FileRemoveDirServiceRequestHandler func(*rclgo.ServiceInfo, *FileRemoveDir_Request, FileRemoveDirServiceResponseSender)

// FileRemoveDirService wraps rclgo.Service to provide type safe helper
// functions
type FileRemoveDirService struct {
	*rclgo.Service
}

// NewFileRemoveDirService creates and returns a new service for the
// FileRemoveDir
func NewFileRemoveDirService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler FileRemoveDirServiceRequestHandler) (*FileRemoveDirService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*FileRemoveDir_Request)
		responseSender := FileRemoveDirServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FileRemoveDirTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FileRemoveDirService{service}, nil
}