// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/file_remove.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/FileRemove_Request", FileRemove_RequestTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/FileRemove_Request", FileRemove_RequestTypeSupport)
}

type FileRemove_Request struct {
	FilePath string `yaml:"file_path"`
}

// NewFileRemove_Request creates a new FileRemove_Request with default values.
func NewFileRemove_Request() *FileRemove_Request {
	self := FileRemove_Request{}
	self.SetDefaults()
	return &self
}

func (t *FileRemove_Request) Clone() *FileRemove_Request {
	c := &FileRemove_Request{}
	c.FilePath = t.FilePath
	return c
}

func (t *FileRemove_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *FileRemove_Request) SetDefaults() {
	t.FilePath = ""
}

func (t *FileRemove_Request) GetTypeSupport() types.MessageTypeSupport {
	return FileRemove_RequestTypeSupport
}

// FileRemove_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type FileRemove_RequestPublisher struct {
	*rclgo.Publisher
}

// NewFileRemove_RequestPublisher creates and returns a new publisher for the
// FileRemove_Request
func NewFileRemove_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*FileRemove_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, FileRemove_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileRemove_RequestPublisher{pub}, nil
}

func (p *FileRemove_RequestPublisher) Publish(msg *FileRemove_Request) error {
	return p.Publisher.Publish(msg)
}

// FileRemove_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type FileRemove_RequestSubscription struct {
	*rclgo.Subscription
}

// FileRemove_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a FileRemove_RequestSubscription.
type FileRemove_RequestSubscriptionCallback func(msg *FileRemove_Request, info *rclgo.MessageInfo, err error)

// NewFileRemove_RequestSubscription creates and returns a new subscription for the
// FileRemove_Request
func NewFileRemove_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback FileRemove_RequestSubscriptionCallback) (*FileRemove_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg FileRemove_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, FileRemove_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FileRemove_RequestSubscription{sub}, nil
}

func (s *FileRemove_RequestSubscription) TakeMessage(out *FileRemove_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFileRemove_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFileRemove_RequestSlice(dst, src []FileRemove_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FileRemove_RequestTypeSupport types.MessageTypeSupport = _FileRemove_RequestTypeSupport{}

type _FileRemove_RequestTypeSupport struct{}

func (t _FileRemove_RequestTypeSupport) New() types.Message {
	return NewFileRemove_Request()
}

func (t _FileRemove_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__FileRemove_Request
	return (unsafe.Pointer)(C.mavros_msgs__srv__FileRemove_Request__create())
}

func (t _FileRemove_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__FileRemove_Request__destroy((*C.mavros_msgs__srv__FileRemove_Request)(pointer_to_free))
}

func (t _FileRemove_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FileRemove_Request)
	mem := (*C.mavros_msgs__srv__FileRemove_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.file_path), m.FilePath)
}

func (t _FileRemove_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FileRemove_Request)
	mem := (*C.mavros_msgs__srv__FileRemove_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.FilePath, unsafe.Pointer(&mem.file_path))
}

func (t _FileRemove_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__FileRemove_Request())
}

type CFileRemove_Request = C.mavros_msgs__srv__FileRemove_Request
type CFileRemove_Request__Sequence = C.mavros_msgs__srv__FileRemove_Request__Sequence

func FileRemove_Request__Sequence_to_Go(goSlice *[]FileRemove_Request, cSlice CFileRemove_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FileRemove_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FileRemove_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func FileRemove_Request__Sequence_to_C(cSlice *CFileRemove_Request__Sequence, goSlice []FileRemove_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__FileRemove_Request)(C.malloc(C.sizeof_struct_mavros_msgs__srv__FileRemove_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FileRemove_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func FileRemove_Request__Array_to_Go(goSlice []FileRemove_Request, cSlice []CFileRemove_Request) {
	for i := 0; i < len(cSlice); i++ {
		FileRemove_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FileRemove_Request__Array_to_C(cSlice []CFileRemove_Request, goSlice []FileRemove_Request) {
	for i := 0; i < len(goSlice); i++ {
		FileRemove_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
