// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/file_write.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/FileWrite_Response", FileWrite_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/FileWrite_Response", FileWrite_ResponseTypeSupport)
}

type FileWrite_Response struct {
	Success bool `yaml:"success"`
	RErrno int32 `yaml:"r_errno"`
}

// NewFileWrite_Response creates a new FileWrite_Response with default values.
func NewFileWrite_Response() *FileWrite_Response {
	self := FileWrite_Response{}
	self.SetDefaults()
	return &self
}

func (t *FileWrite_Response) Clone() *FileWrite_Response {
	c := &FileWrite_Response{}
	c.Success = t.Success
	c.RErrno = t.RErrno
	return c
}

func (t *FileWrite_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *FileWrite_Response) SetDefaults() {
	t.Success = false
	t.RErrno = 0
}

func (t *FileWrite_Response) GetTypeSupport() types.MessageTypeSupport {
	return FileWrite_ResponseTypeSupport
}

// FileWrite_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type FileWrite_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewFileWrite_ResponsePublisher creates and returns a new publisher for the
// FileWrite_Response
func NewFileWrite_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*FileWrite_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, FileWrite_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileWrite_ResponsePublisher{pub}, nil
}

func (p *FileWrite_ResponsePublisher) Publish(msg *FileWrite_Response) error {
	return p.Publisher.Publish(msg)
}

// FileWrite_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type FileWrite_ResponseSubscription struct {
	*rclgo.Subscription
}

// FileWrite_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a FileWrite_ResponseSubscription.
type FileWrite_ResponseSubscriptionCallback func(msg *FileWrite_Response, info *rclgo.MessageInfo, err error)

// NewFileWrite_ResponseSubscription creates and returns a new subscription for the
// FileWrite_Response
func NewFileWrite_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback FileWrite_ResponseSubscriptionCallback) (*FileWrite_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg FileWrite_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, FileWrite_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FileWrite_ResponseSubscription{sub}, nil
}

func (s *FileWrite_ResponseSubscription) TakeMessage(out *FileWrite_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFileWrite_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFileWrite_ResponseSlice(dst, src []FileWrite_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FileWrite_ResponseTypeSupport types.MessageTypeSupport = _FileWrite_ResponseTypeSupport{}

type _FileWrite_ResponseTypeSupport struct{}

func (t _FileWrite_ResponseTypeSupport) New() types.Message {
	return NewFileWrite_Response()
}

func (t _FileWrite_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__FileWrite_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__FileWrite_Response__create())
}

func (t _FileWrite_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__FileWrite_Response__destroy((*C.mavros_msgs__srv__FileWrite_Response)(pointer_to_free))
}

func (t _FileWrite_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FileWrite_Response)
	mem := (*C.mavros_msgs__srv__FileWrite_Response)(dst)
	mem.success = C.bool(m.Success)
	mem.r_errno = C.int32_t(m.RErrno)
}

func (t _FileWrite_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FileWrite_Response)
	mem := (*C.mavros_msgs__srv__FileWrite_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	m.RErrno = int32(mem.r_errno)
}

func (t _FileWrite_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__FileWrite_Response())
}

type CFileWrite_Response = C.mavros_msgs__srv__FileWrite_Response
type CFileWrite_Response__Sequence = C.mavros_msgs__srv__FileWrite_Response__Sequence

func FileWrite_Response__Sequence_to_Go(goSlice *[]FileWrite_Response, cSlice CFileWrite_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FileWrite_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FileWrite_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func FileWrite_Response__Sequence_to_C(cSlice *CFileWrite_Response__Sequence, goSlice []FileWrite_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__FileWrite_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__FileWrite_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FileWrite_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func FileWrite_Response__Array_to_Go(goSlice []FileWrite_Response, cSlice []CFileWrite_Response) {
	for i := 0; i < len(cSlice); i++ {
		FileWrite_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FileWrite_Response__Array_to_C(cSlice []CFileWrite_Response, goSlice []FileWrite_Response) {
	for i := 0; i < len(goSlice); i++ {
		FileWrite_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
