// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <mavros_msgs/srv/file_read.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("mavros_msgs/FileRead", FileReadTypeSupport)
	typemap.RegisterService("mavros_msgs/srv/FileRead", FileReadTypeSupport)
}

type _FileReadTypeSupport struct {}

func (s _FileReadTypeSupport) Request() types.MessageTypeSupport {
	return FileRead_RequestTypeSupport
}

func (s _FileReadTypeSupport) Response() types.MessageTypeSupport {
	return FileRead_ResponseTypeSupport
}

func (s _FileReadTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__mavros_msgs__srv__FileRead())
}

// Modifying this variable is undefined behavior.
var FileReadTypeSupport types.ServiceTypeSupport = _FileReadTypeSupport{}

// FileReadClient wraps rclgo.Client to provide type safe helper
// functions
type FileReadClient struct {
	*rclgo.Client
}

// NewFileReadClient creates and returns a new client for the
// FileRead
func NewFileReadClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*FileReadClient, error) {
	client, err := node.NewClient(serviceName, FileReadTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileReadClient{client}, nil
}

func (s *FileReadClient) Send(ctx context.Context, req *FileRead_Request) (*FileRead_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FileRead_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FileReadServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s FileReadServiceResponseSender) SendResponse(resp *FileRead_Response) error {
	return s.sender.SendResponse(resp)
}

type FileReadServiceRequestHandler func(*rclgo.ServiceInfo, *FileRead_Request, FileReadServiceResponseSender)

// FileReadService wraps rclgo.Service to provide type safe helper
// functions
type FileReadService struct {
	*rclgo.Service
}

// NewFileReadService creates and returns a new service for the
// FileRead
func NewFileReadService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler FileReadServiceRequestHandler) (*FileReadService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*FileRead_Request)
		responseSender := FileReadServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FileReadTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FileReadService{service}, nil
}