// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/file_close.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/FileClose_Request", FileClose_RequestTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/FileClose_Request", FileClose_RequestTypeSupport)
}

type FileClose_Request struct {
	FilePath string `yaml:"file_path"`
}

// NewFileClose_Request creates a new FileClose_Request with default values.
func NewFileClose_Request() *FileClose_Request {
	self := FileClose_Request{}
	self.SetDefaults()
	return &self
}

func (t *FileClose_Request) Clone() *FileClose_Request {
	c := &FileClose_Request{}
	c.FilePath = t.FilePath
	return c
}

func (t *FileClose_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *FileClose_Request) SetDefaults() {
	t.FilePath = ""
}

func (t *FileClose_Request) GetTypeSupport() types.MessageTypeSupport {
	return FileClose_RequestTypeSupport
}

// FileClose_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type FileClose_RequestPublisher struct {
	*rclgo.Publisher
}

// NewFileClose_RequestPublisher creates and returns a new publisher for the
// FileClose_Request
func NewFileClose_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*FileClose_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, FileClose_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileClose_RequestPublisher{pub}, nil
}

func (p *FileClose_RequestPublisher) Publish(msg *FileClose_Request) error {
	return p.Publisher.Publish(msg)
}

// FileClose_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type FileClose_RequestSubscription struct {
	*rclgo.Subscription
}

// FileClose_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a FileClose_RequestSubscription.
type FileClose_RequestSubscriptionCallback func(msg *FileClose_Request, info *rclgo.MessageInfo, err error)

// NewFileClose_RequestSubscription creates and returns a new subscription for the
// FileClose_Request
func NewFileClose_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback FileClose_RequestSubscriptionCallback) (*FileClose_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg FileClose_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, FileClose_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FileClose_RequestSubscription{sub}, nil
}

func (s *FileClose_RequestSubscription) TakeMessage(out *FileClose_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFileClose_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFileClose_RequestSlice(dst, src []FileClose_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FileClose_RequestTypeSupport types.MessageTypeSupport = _FileClose_RequestTypeSupport{}

type _FileClose_RequestTypeSupport struct{}

func (t _FileClose_RequestTypeSupport) New() types.Message {
	return NewFileClose_Request()
}

func (t _FileClose_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__FileClose_Request
	return (unsafe.Pointer)(C.mavros_msgs__srv__FileClose_Request__create())
}

func (t _FileClose_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__FileClose_Request__destroy((*C.mavros_msgs__srv__FileClose_Request)(pointer_to_free))
}

func (t _FileClose_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FileClose_Request)
	mem := (*C.mavros_msgs__srv__FileClose_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.file_path), m.FilePath)
}

func (t _FileClose_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FileClose_Request)
	mem := (*C.mavros_msgs__srv__FileClose_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.FilePath, unsafe.Pointer(&mem.file_path))
}

func (t _FileClose_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__FileClose_Request())
}

type CFileClose_Request = C.mavros_msgs__srv__FileClose_Request
type CFileClose_Request__Sequence = C.mavros_msgs__srv__FileClose_Request__Sequence

func FileClose_Request__Sequence_to_Go(goSlice *[]FileClose_Request, cSlice CFileClose_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FileClose_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FileClose_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func FileClose_Request__Sequence_to_C(cSlice *CFileClose_Request__Sequence, goSlice []FileClose_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__FileClose_Request)(C.malloc(C.sizeof_struct_mavros_msgs__srv__FileClose_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FileClose_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func FileClose_Request__Array_to_Go(goSlice []FileClose_Request, cSlice []CFileClose_Request) {
	for i := 0; i < len(cSlice); i++ {
		FileClose_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FileClose_Request__Array_to_C(cSlice []CFileClose_Request, goSlice []FileClose_Request) {
	for i := 0; i < len(goSlice); i++ {
		FileClose_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
