// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/gimbal_get_information.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/GimbalGetInformation_Response", GimbalGetInformation_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/GimbalGetInformation_Response", GimbalGetInformation_ResponseTypeSupport)
}

type GimbalGetInformation_Response struct {
	Success bool `yaml:"success"`
	Result uint8 `yaml:"result"`// raw result returned by COMMAND_ACK
}

// NewGimbalGetInformation_Response creates a new GimbalGetInformation_Response with default values.
func NewGimbalGetInformation_Response() *GimbalGetInformation_Response {
	self := GimbalGetInformation_Response{}
	self.SetDefaults()
	return &self
}

func (t *GimbalGetInformation_Response) Clone() *GimbalGetInformation_Response {
	c := &GimbalGetInformation_Response{}
	c.Success = t.Success
	c.Result = t.Result
	return c
}

func (t *GimbalGetInformation_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GimbalGetInformation_Response) SetDefaults() {
	t.Success = false
	t.Result = 0
}

func (t *GimbalGetInformation_Response) GetTypeSupport() types.MessageTypeSupport {
	return GimbalGetInformation_ResponseTypeSupport
}

// GimbalGetInformation_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GimbalGetInformation_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGimbalGetInformation_ResponsePublisher creates and returns a new publisher for the
// GimbalGetInformation_Response
func NewGimbalGetInformation_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GimbalGetInformation_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GimbalGetInformation_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GimbalGetInformation_ResponsePublisher{pub}, nil
}

func (p *GimbalGetInformation_ResponsePublisher) Publish(msg *GimbalGetInformation_Response) error {
	return p.Publisher.Publish(msg)
}

// GimbalGetInformation_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GimbalGetInformation_ResponseSubscription struct {
	*rclgo.Subscription
}

// GimbalGetInformation_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GimbalGetInformation_ResponseSubscription.
type GimbalGetInformation_ResponseSubscriptionCallback func(msg *GimbalGetInformation_Response, info *rclgo.MessageInfo, err error)

// NewGimbalGetInformation_ResponseSubscription creates and returns a new subscription for the
// GimbalGetInformation_Response
func NewGimbalGetInformation_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GimbalGetInformation_ResponseSubscriptionCallback) (*GimbalGetInformation_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GimbalGetInformation_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GimbalGetInformation_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GimbalGetInformation_ResponseSubscription{sub}, nil
}

func (s *GimbalGetInformation_ResponseSubscription) TakeMessage(out *GimbalGetInformation_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGimbalGetInformation_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGimbalGetInformation_ResponseSlice(dst, src []GimbalGetInformation_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GimbalGetInformation_ResponseTypeSupport types.MessageTypeSupport = _GimbalGetInformation_ResponseTypeSupport{}

type _GimbalGetInformation_ResponseTypeSupport struct{}

func (t _GimbalGetInformation_ResponseTypeSupport) New() types.Message {
	return NewGimbalGetInformation_Response()
}

func (t _GimbalGetInformation_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__GimbalGetInformation_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__GimbalGetInformation_Response__create())
}

func (t _GimbalGetInformation_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__GimbalGetInformation_Response__destroy((*C.mavros_msgs__srv__GimbalGetInformation_Response)(pointer_to_free))
}

func (t _GimbalGetInformation_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GimbalGetInformation_Response)
	mem := (*C.mavros_msgs__srv__GimbalGetInformation_Response)(dst)
	mem.success = C.bool(m.Success)
	mem.result = C.uint8_t(m.Result)
}

func (t _GimbalGetInformation_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GimbalGetInformation_Response)
	mem := (*C.mavros_msgs__srv__GimbalGetInformation_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	m.Result = uint8(mem.result)
}

func (t _GimbalGetInformation_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__GimbalGetInformation_Response())
}

type CGimbalGetInformation_Response = C.mavros_msgs__srv__GimbalGetInformation_Response
type CGimbalGetInformation_Response__Sequence = C.mavros_msgs__srv__GimbalGetInformation_Response__Sequence

func GimbalGetInformation_Response__Sequence_to_Go(goSlice *[]GimbalGetInformation_Response, cSlice CGimbalGetInformation_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GimbalGetInformation_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GimbalGetInformation_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GimbalGetInformation_Response__Sequence_to_C(cSlice *CGimbalGetInformation_Response__Sequence, goSlice []GimbalGetInformation_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__GimbalGetInformation_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__GimbalGetInformation_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GimbalGetInformation_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GimbalGetInformation_Response__Array_to_Go(goSlice []GimbalGetInformation_Response, cSlice []CGimbalGetInformation_Response) {
	for i := 0; i < len(cSlice); i++ {
		GimbalGetInformation_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GimbalGetInformation_Response__Array_to_C(cSlice []CGimbalGetInformation_Response, goSlice []GimbalGetInformation_Response) {
	for i := 0; i < len(goSlice); i++ {
		GimbalGetInformation_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
