// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/log_request_end.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/LogRequestEnd_Response", LogRequestEnd_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/LogRequestEnd_Response", LogRequestEnd_ResponseTypeSupport)
}

type LogRequestEnd_Response struct {
	Success bool `yaml:"success"`
}

// NewLogRequestEnd_Response creates a new LogRequestEnd_Response with default values.
func NewLogRequestEnd_Response() *LogRequestEnd_Response {
	self := LogRequestEnd_Response{}
	self.SetDefaults()
	return &self
}

func (t *LogRequestEnd_Response) Clone() *LogRequestEnd_Response {
	c := &LogRequestEnd_Response{}
	c.Success = t.Success
	return c
}

func (t *LogRequestEnd_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *LogRequestEnd_Response) SetDefaults() {
	t.Success = false
}

func (t *LogRequestEnd_Response) GetTypeSupport() types.MessageTypeSupport {
	return LogRequestEnd_ResponseTypeSupport
}

// LogRequestEnd_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type LogRequestEnd_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewLogRequestEnd_ResponsePublisher creates and returns a new publisher for the
// LogRequestEnd_Response
func NewLogRequestEnd_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*LogRequestEnd_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, LogRequestEnd_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &LogRequestEnd_ResponsePublisher{pub}, nil
}

func (p *LogRequestEnd_ResponsePublisher) Publish(msg *LogRequestEnd_Response) error {
	return p.Publisher.Publish(msg)
}

// LogRequestEnd_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type LogRequestEnd_ResponseSubscription struct {
	*rclgo.Subscription
}

// LogRequestEnd_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a LogRequestEnd_ResponseSubscription.
type LogRequestEnd_ResponseSubscriptionCallback func(msg *LogRequestEnd_Response, info *rclgo.MessageInfo, err error)

// NewLogRequestEnd_ResponseSubscription creates and returns a new subscription for the
// LogRequestEnd_Response
func NewLogRequestEnd_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback LogRequestEnd_ResponseSubscriptionCallback) (*LogRequestEnd_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg LogRequestEnd_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, LogRequestEnd_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &LogRequestEnd_ResponseSubscription{sub}, nil
}

func (s *LogRequestEnd_ResponseSubscription) TakeMessage(out *LogRequestEnd_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneLogRequestEnd_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneLogRequestEnd_ResponseSlice(dst, src []LogRequestEnd_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var LogRequestEnd_ResponseTypeSupport types.MessageTypeSupport = _LogRequestEnd_ResponseTypeSupport{}

type _LogRequestEnd_ResponseTypeSupport struct{}

func (t _LogRequestEnd_ResponseTypeSupport) New() types.Message {
	return NewLogRequestEnd_Response()
}

func (t _LogRequestEnd_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__LogRequestEnd_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__LogRequestEnd_Response__create())
}

func (t _LogRequestEnd_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__LogRequestEnd_Response__destroy((*C.mavros_msgs__srv__LogRequestEnd_Response)(pointer_to_free))
}

func (t _LogRequestEnd_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*LogRequestEnd_Response)
	mem := (*C.mavros_msgs__srv__LogRequestEnd_Response)(dst)
	mem.success = C.bool(m.Success)
}

func (t _LogRequestEnd_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*LogRequestEnd_Response)
	mem := (*C.mavros_msgs__srv__LogRequestEnd_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
}

func (t _LogRequestEnd_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__LogRequestEnd_Response())
}

type CLogRequestEnd_Response = C.mavros_msgs__srv__LogRequestEnd_Response
type CLogRequestEnd_Response__Sequence = C.mavros_msgs__srv__LogRequestEnd_Response__Sequence

func LogRequestEnd_Response__Sequence_to_Go(goSlice *[]LogRequestEnd_Response, cSlice CLogRequestEnd_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]LogRequestEnd_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		LogRequestEnd_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func LogRequestEnd_Response__Sequence_to_C(cSlice *CLogRequestEnd_Response__Sequence, goSlice []LogRequestEnd_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__LogRequestEnd_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__LogRequestEnd_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		LogRequestEnd_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func LogRequestEnd_Response__Array_to_Go(goSlice []LogRequestEnd_Response, cSlice []CLogRequestEnd_Response) {
	for i := 0; i < len(cSlice); i++ {
		LogRequestEnd_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func LogRequestEnd_Response__Array_to_C(cSlice []CLogRequestEnd_Response, goSlice []LogRequestEnd_Response) {
	for i := 0; i < len(goSlice); i++ {
		LogRequestEnd_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
