// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	mavros_msgs_msg "test/msgs/mavros_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/param_get.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/ParamGet_Response", ParamGet_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/ParamGet_Response", ParamGet_ResponseTypeSupport)
}

type ParamGet_Response struct {
	Success bool `yaml:"success"`
	Value mavros_msgs_msg.ParamValue `yaml:"value"`
}

// NewParamGet_Response creates a new ParamGet_Response with default values.
func NewParamGet_Response() *ParamGet_Response {
	self := ParamGet_Response{}
	self.SetDefaults()
	return &self
}

func (t *ParamGet_Response) Clone() *ParamGet_Response {
	c := &ParamGet_Response{}
	c.Success = t.Success
	c.Value = *t.Value.Clone()
	return c
}

func (t *ParamGet_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ParamGet_Response) SetDefaults() {
	t.Success = false
	t.Value.SetDefaults()
}

func (t *ParamGet_Response) GetTypeSupport() types.MessageTypeSupport {
	return ParamGet_ResponseTypeSupport
}

// ParamGet_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ParamGet_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewParamGet_ResponsePublisher creates and returns a new publisher for the
// ParamGet_Response
func NewParamGet_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ParamGet_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ParamGet_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ParamGet_ResponsePublisher{pub}, nil
}

func (p *ParamGet_ResponsePublisher) Publish(msg *ParamGet_Response) error {
	return p.Publisher.Publish(msg)
}

// ParamGet_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ParamGet_ResponseSubscription struct {
	*rclgo.Subscription
}

// ParamGet_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ParamGet_ResponseSubscription.
type ParamGet_ResponseSubscriptionCallback func(msg *ParamGet_Response, info *rclgo.MessageInfo, err error)

// NewParamGet_ResponseSubscription creates and returns a new subscription for the
// ParamGet_Response
func NewParamGet_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ParamGet_ResponseSubscriptionCallback) (*ParamGet_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ParamGet_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ParamGet_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ParamGet_ResponseSubscription{sub}, nil
}

func (s *ParamGet_ResponseSubscription) TakeMessage(out *ParamGet_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneParamGet_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneParamGet_ResponseSlice(dst, src []ParamGet_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ParamGet_ResponseTypeSupport types.MessageTypeSupport = _ParamGet_ResponseTypeSupport{}

type _ParamGet_ResponseTypeSupport struct{}

func (t _ParamGet_ResponseTypeSupport) New() types.Message {
	return NewParamGet_Response()
}

func (t _ParamGet_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__ParamGet_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__ParamGet_Response__create())
}

func (t _ParamGet_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__ParamGet_Response__destroy((*C.mavros_msgs__srv__ParamGet_Response)(pointer_to_free))
}

func (t _ParamGet_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ParamGet_Response)
	mem := (*C.mavros_msgs__srv__ParamGet_Response)(dst)
	mem.success = C.bool(m.Success)
	mavros_msgs_msg.ParamValueTypeSupport.AsCStruct(unsafe.Pointer(&mem.value), &m.Value)
}

func (t _ParamGet_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ParamGet_Response)
	mem := (*C.mavros_msgs__srv__ParamGet_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	mavros_msgs_msg.ParamValueTypeSupport.AsGoStruct(&m.Value, unsafe.Pointer(&mem.value))
}

func (t _ParamGet_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__ParamGet_Response())
}

type CParamGet_Response = C.mavros_msgs__srv__ParamGet_Response
type CParamGet_Response__Sequence = C.mavros_msgs__srv__ParamGet_Response__Sequence

func ParamGet_Response__Sequence_to_Go(goSlice *[]ParamGet_Response, cSlice CParamGet_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ParamGet_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ParamGet_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ParamGet_Response__Sequence_to_C(cSlice *CParamGet_Response__Sequence, goSlice []ParamGet_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__ParamGet_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__ParamGet_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ParamGet_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ParamGet_Response__Array_to_Go(goSlice []ParamGet_Response, cSlice []CParamGet_Response) {
	for i := 0; i < len(cSlice); i++ {
		ParamGet_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ParamGet_Response__Array_to_C(cSlice []CParamGet_Response, goSlice []ParamGet_Response) {
	for i := 0; i < len(goSlice); i++ {
		ParamGet_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
