// Code generated by rclgo-gen. DO NOT EDIT.

package turtlesim_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "test/msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <turtlesim/action/rotate_absolute.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("turtlesim/RotateAbsolute_SendGoal_Response", RotateAbsolute_SendGoal_ResponseTypeSupport)
	typemap.RegisterMessage("turtlesim/action/RotateAbsolute_SendGoal_Response", RotateAbsolute_SendGoal_ResponseTypeSupport)
}

type RotateAbsolute_SendGoal_Response struct {
	Accepted bool `yaml:"accepted"`
	Stamp builtin_interfaces_msg.Time `yaml:"stamp"`
}

// NewRotateAbsolute_SendGoal_Response creates a new RotateAbsolute_SendGoal_Response with default values.
func NewRotateAbsolute_SendGoal_Response() *RotateAbsolute_SendGoal_Response {
	self := RotateAbsolute_SendGoal_Response{}
	self.SetDefaults()
	return &self
}

func (t *RotateAbsolute_SendGoal_Response) Clone() *RotateAbsolute_SendGoal_Response {
	c := &RotateAbsolute_SendGoal_Response{}
	c.Accepted = t.Accepted
	c.Stamp = *t.Stamp.Clone()
	return c
}

func (t *RotateAbsolute_SendGoal_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *RotateAbsolute_SendGoal_Response) SetDefaults() {
	t.Accepted = false
	t.Stamp.SetDefaults()
}

func (t *RotateAbsolute_SendGoal_Response) GetTypeSupport() types.MessageTypeSupport {
	return RotateAbsolute_SendGoal_ResponseTypeSupport
}
func (t *RotateAbsolute_SendGoal_Response) GetGoalAccepted() bool {
	return t.Accepted
}

// RotateAbsolute_SendGoal_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type RotateAbsolute_SendGoal_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewRotateAbsolute_SendGoal_ResponsePublisher creates and returns a new publisher for the
// RotateAbsolute_SendGoal_Response
func NewRotateAbsolute_SendGoal_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*RotateAbsolute_SendGoal_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, RotateAbsolute_SendGoal_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &RotateAbsolute_SendGoal_ResponsePublisher{pub}, nil
}

func (p *RotateAbsolute_SendGoal_ResponsePublisher) Publish(msg *RotateAbsolute_SendGoal_Response) error {
	return p.Publisher.Publish(msg)
}

// RotateAbsolute_SendGoal_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type RotateAbsolute_SendGoal_ResponseSubscription struct {
	*rclgo.Subscription
}

// RotateAbsolute_SendGoal_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a RotateAbsolute_SendGoal_ResponseSubscription.
type RotateAbsolute_SendGoal_ResponseSubscriptionCallback func(msg *RotateAbsolute_SendGoal_Response, info *rclgo.MessageInfo, err error)

// NewRotateAbsolute_SendGoal_ResponseSubscription creates and returns a new subscription for the
// RotateAbsolute_SendGoal_Response
func NewRotateAbsolute_SendGoal_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback RotateAbsolute_SendGoal_ResponseSubscriptionCallback) (*RotateAbsolute_SendGoal_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg RotateAbsolute_SendGoal_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, RotateAbsolute_SendGoal_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &RotateAbsolute_SendGoal_ResponseSubscription{sub}, nil
}

func (s *RotateAbsolute_SendGoal_ResponseSubscription) TakeMessage(out *RotateAbsolute_SendGoal_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneRotateAbsolute_SendGoal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneRotateAbsolute_SendGoal_ResponseSlice(dst, src []RotateAbsolute_SendGoal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var RotateAbsolute_SendGoal_ResponseTypeSupport types.MessageTypeSupport = _RotateAbsolute_SendGoal_ResponseTypeSupport{}

type _RotateAbsolute_SendGoal_ResponseTypeSupport struct{}

func (t _RotateAbsolute_SendGoal_ResponseTypeSupport) New() types.Message {
	return NewRotateAbsolute_SendGoal_Response()
}

func (t _RotateAbsolute_SendGoal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.turtlesim__action__RotateAbsolute_SendGoal_Response
	return (unsafe.Pointer)(C.turtlesim__action__RotateAbsolute_SendGoal_Response__create())
}

func (t _RotateAbsolute_SendGoal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.turtlesim__action__RotateAbsolute_SendGoal_Response__destroy((*C.turtlesim__action__RotateAbsolute_SendGoal_Response)(pointer_to_free))
}

func (t _RotateAbsolute_SendGoal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*RotateAbsolute_SendGoal_Response)
	mem := (*C.turtlesim__action__RotateAbsolute_SendGoal_Response)(dst)
	mem.accepted = C.bool(m.Accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.stamp), &m.Stamp)
}

func (t _RotateAbsolute_SendGoal_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*RotateAbsolute_SendGoal_Response)
	mem := (*C.turtlesim__action__RotateAbsolute_SendGoal_Response)(ros2_message_buffer)
	m.Accepted = bool(mem.accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Stamp, unsafe.Pointer(&mem.stamp))
}

func (t _RotateAbsolute_SendGoal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__turtlesim__action__RotateAbsolute_SendGoal_Response())
}

type CRotateAbsolute_SendGoal_Response = C.turtlesim__action__RotateAbsolute_SendGoal_Response
type CRotateAbsolute_SendGoal_Response__Sequence = C.turtlesim__action__RotateAbsolute_SendGoal_Response__Sequence

func RotateAbsolute_SendGoal_Response__Sequence_to_Go(goSlice *[]RotateAbsolute_SendGoal_Response, cSlice CRotateAbsolute_SendGoal_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]RotateAbsolute_SendGoal_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		RotateAbsolute_SendGoal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func RotateAbsolute_SendGoal_Response__Sequence_to_C(cSlice *CRotateAbsolute_SendGoal_Response__Sequence, goSlice []RotateAbsolute_SendGoal_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.turtlesim__action__RotateAbsolute_SendGoal_Response)(C.malloc(C.sizeof_struct_turtlesim__action__RotateAbsolute_SendGoal_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		RotateAbsolute_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func RotateAbsolute_SendGoal_Response__Array_to_Go(goSlice []RotateAbsolute_SendGoal_Response, cSlice []CRotateAbsolute_SendGoal_Response) {
	for i := 0; i < len(cSlice); i++ {
		RotateAbsolute_SendGoal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func RotateAbsolute_SendGoal_Response__Array_to_C(cSlice []CRotateAbsolute_SendGoal_Response, goSlice []RotateAbsolute_SendGoal_Response) {
	for i := 0; i < len(goSlice); i++ {
		RotateAbsolute_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
