// Code generated by rclgo-gen. DO NOT EDIT.

package turtlesim_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <turtlesim/srv/set_pen.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("turtlesim/SetPen_Request", SetPen_RequestTypeSupport)
	typemap.RegisterMessage("turtlesim/srv/SetPen_Request", SetPen_RequestTypeSupport)
}

type SetPen_Request struct {
	R uint8 `yaml:"r"`
	G uint8 `yaml:"g"`
	B uint8 `yaml:"b"`
	Width uint8 `yaml:"width"`
	Off uint8 `yaml:"off"`
}

// NewSetPen_Request creates a new SetPen_Request with default values.
func NewSetPen_Request() *SetPen_Request {
	self := SetPen_Request{}
	self.SetDefaults()
	return &self
}

func (t *SetPen_Request) Clone() *SetPen_Request {
	c := &SetPen_Request{}
	c.R = t.R
	c.G = t.G
	c.B = t.B
	c.Width = t.Width
	c.Off = t.Off
	return c
}

func (t *SetPen_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetPen_Request) SetDefaults() {
	t.R = 0
	t.G = 0
	t.B = 0
	t.Width = 0
	t.Off = 0
}

func (t *SetPen_Request) GetTypeSupport() types.MessageTypeSupport {
	return SetPen_RequestTypeSupport
}

// SetPen_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetPen_RequestPublisher struct {
	*rclgo.Publisher
}

// NewSetPen_RequestPublisher creates and returns a new publisher for the
// SetPen_Request
func NewSetPen_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetPen_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetPen_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetPen_RequestPublisher{pub}, nil
}

func (p *SetPen_RequestPublisher) Publish(msg *SetPen_Request) error {
	return p.Publisher.Publish(msg)
}

// SetPen_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetPen_RequestSubscription struct {
	*rclgo.Subscription
}

// SetPen_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a SetPen_RequestSubscription.
type SetPen_RequestSubscriptionCallback func(msg *SetPen_Request, info *rclgo.MessageInfo, err error)

// NewSetPen_RequestSubscription creates and returns a new subscription for the
// SetPen_Request
func NewSetPen_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetPen_RequestSubscriptionCallback) (*SetPen_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetPen_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetPen_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetPen_RequestSubscription{sub}, nil
}

func (s *SetPen_RequestSubscription) TakeMessage(out *SetPen_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetPen_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetPen_RequestSlice(dst, src []SetPen_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetPen_RequestTypeSupport types.MessageTypeSupport = _SetPen_RequestTypeSupport{}

type _SetPen_RequestTypeSupport struct{}

func (t _SetPen_RequestTypeSupport) New() types.Message {
	return NewSetPen_Request()
}

func (t _SetPen_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.turtlesim__srv__SetPen_Request
	return (unsafe.Pointer)(C.turtlesim__srv__SetPen_Request__create())
}

func (t _SetPen_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.turtlesim__srv__SetPen_Request__destroy((*C.turtlesim__srv__SetPen_Request)(pointer_to_free))
}

func (t _SetPen_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetPen_Request)
	mem := (*C.turtlesim__srv__SetPen_Request)(dst)
	mem.r = C.uint8_t(m.R)
	mem.g = C.uint8_t(m.G)
	mem.b = C.uint8_t(m.B)
	mem.width = C.uint8_t(m.Width)
	mem.off = C.uint8_t(m.Off)
}

func (t _SetPen_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetPen_Request)
	mem := (*C.turtlesim__srv__SetPen_Request)(ros2_message_buffer)
	m.R = uint8(mem.r)
	m.G = uint8(mem.g)
	m.B = uint8(mem.b)
	m.Width = uint8(mem.width)
	m.Off = uint8(mem.off)
}

func (t _SetPen_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__turtlesim__srv__SetPen_Request())
}

type CSetPen_Request = C.turtlesim__srv__SetPen_Request
type CSetPen_Request__Sequence = C.turtlesim__srv__SetPen_Request__Sequence

func SetPen_Request__Sequence_to_Go(goSlice *[]SetPen_Request, cSlice CSetPen_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetPen_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetPen_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetPen_Request__Sequence_to_C(cSlice *CSetPen_Request__Sequence, goSlice []SetPen_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.turtlesim__srv__SetPen_Request)(C.malloc(C.sizeof_struct_turtlesim__srv__SetPen_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetPen_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetPen_Request__Array_to_Go(goSlice []SetPen_Request, cSlice []CSetPen_Request) {
	for i := 0; i < len(cSlice); i++ {
		SetPen_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetPen_Request__Array_to_C(cSlice []CSetPen_Request, goSlice []SetPen_Request) {
	for i := 0; i < len(goSlice); i++ {
		SetPen_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
