// Code generated by rclgo-gen. DO NOT EDIT.

package turtlesim_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <turtlesim/srv/teleport_absolute.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("turtlesim/TeleportAbsolute_Response", TeleportAbsolute_ResponseTypeSupport)
	typemap.RegisterMessage("turtlesim/srv/TeleportAbsolute_Response", TeleportAbsolute_ResponseTypeSupport)
}

type TeleportAbsolute_Response struct {
}

// NewTeleportAbsolute_Response creates a new TeleportAbsolute_Response with default values.
func NewTeleportAbsolute_Response() *TeleportAbsolute_Response {
	self := TeleportAbsolute_Response{}
	self.SetDefaults()
	return &self
}

func (t *TeleportAbsolute_Response) Clone() *TeleportAbsolute_Response {
	c := &TeleportAbsolute_Response{}
	return c
}

func (t *TeleportAbsolute_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *TeleportAbsolute_Response) SetDefaults() {
}

func (t *TeleportAbsolute_Response) GetTypeSupport() types.MessageTypeSupport {
	return TeleportAbsolute_ResponseTypeSupport
}

// TeleportAbsolute_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type TeleportAbsolute_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewTeleportAbsolute_ResponsePublisher creates and returns a new publisher for the
// TeleportAbsolute_Response
func NewTeleportAbsolute_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*TeleportAbsolute_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, TeleportAbsolute_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &TeleportAbsolute_ResponsePublisher{pub}, nil
}

func (p *TeleportAbsolute_ResponsePublisher) Publish(msg *TeleportAbsolute_Response) error {
	return p.Publisher.Publish(msg)
}

// TeleportAbsolute_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type TeleportAbsolute_ResponseSubscription struct {
	*rclgo.Subscription
}

// TeleportAbsolute_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a TeleportAbsolute_ResponseSubscription.
type TeleportAbsolute_ResponseSubscriptionCallback func(msg *TeleportAbsolute_Response, info *rclgo.MessageInfo, err error)

// NewTeleportAbsolute_ResponseSubscription creates and returns a new subscription for the
// TeleportAbsolute_Response
func NewTeleportAbsolute_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback TeleportAbsolute_ResponseSubscriptionCallback) (*TeleportAbsolute_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg TeleportAbsolute_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, TeleportAbsolute_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &TeleportAbsolute_ResponseSubscription{sub}, nil
}

func (s *TeleportAbsolute_ResponseSubscription) TakeMessage(out *TeleportAbsolute_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneTeleportAbsolute_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneTeleportAbsolute_ResponseSlice(dst, src []TeleportAbsolute_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var TeleportAbsolute_ResponseTypeSupport types.MessageTypeSupport = _TeleportAbsolute_ResponseTypeSupport{}

type _TeleportAbsolute_ResponseTypeSupport struct{}

func (t _TeleportAbsolute_ResponseTypeSupport) New() types.Message {
	return NewTeleportAbsolute_Response()
}

func (t _TeleportAbsolute_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.turtlesim__srv__TeleportAbsolute_Response
	return (unsafe.Pointer)(C.turtlesim__srv__TeleportAbsolute_Response__create())
}

func (t _TeleportAbsolute_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.turtlesim__srv__TeleportAbsolute_Response__destroy((*C.turtlesim__srv__TeleportAbsolute_Response)(pointer_to_free))
}

func (t _TeleportAbsolute_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _TeleportAbsolute_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _TeleportAbsolute_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__turtlesim__srv__TeleportAbsolute_Response())
}

type CTeleportAbsolute_Response = C.turtlesim__srv__TeleportAbsolute_Response
type CTeleportAbsolute_Response__Sequence = C.turtlesim__srv__TeleportAbsolute_Response__Sequence

func TeleportAbsolute_Response__Sequence_to_Go(goSlice *[]TeleportAbsolute_Response, cSlice CTeleportAbsolute_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]TeleportAbsolute_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		TeleportAbsolute_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func TeleportAbsolute_Response__Sequence_to_C(cSlice *CTeleportAbsolute_Response__Sequence, goSlice []TeleportAbsolute_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.turtlesim__srv__TeleportAbsolute_Response)(C.malloc(C.sizeof_struct_turtlesim__srv__TeleportAbsolute_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		TeleportAbsolute_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func TeleportAbsolute_Response__Array_to_Go(goSlice []TeleportAbsolute_Response, cSlice []CTeleportAbsolute_Response) {
	for i := 0; i < len(cSlice); i++ {
		TeleportAbsolute_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func TeleportAbsolute_Response__Array_to_C(cSlice []CTeleportAbsolute_Response, goSlice []TeleportAbsolute_Response) {
	for i := 0; i < len(goSlice); i++ {
		TeleportAbsolute_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
