// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/command_ack.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/CommandAck_Response", CommandAck_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/CommandAck_Response", CommandAck_ResponseTypeSupport)
}

type CommandAck_Response struct {
	Success bool `yaml:"success"`
	Result uint8 `yaml:"result"`// raw result returned by COMMAND_ACK
}

// NewCommandAck_Response creates a new CommandAck_Response with default values.
func NewCommandAck_Response() *CommandAck_Response {
	self := CommandAck_Response{}
	self.SetDefaults()
	return &self
}

func (t *CommandAck_Response) Clone() *CommandAck_Response {
	c := &CommandAck_Response{}
	c.Success = t.Success
	c.Result = t.Result
	return c
}

func (t *CommandAck_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *CommandAck_Response) SetDefaults() {
	t.Success = false
	t.Result = 0
}

func (t *CommandAck_Response) GetTypeSupport() types.MessageTypeSupport {
	return CommandAck_ResponseTypeSupport
}

// CommandAck_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type CommandAck_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewCommandAck_ResponsePublisher creates and returns a new publisher for the
// CommandAck_Response
func NewCommandAck_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*CommandAck_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, CommandAck_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &CommandAck_ResponsePublisher{pub}, nil
}

func (p *CommandAck_ResponsePublisher) Publish(msg *CommandAck_Response) error {
	return p.Publisher.Publish(msg)
}

// CommandAck_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type CommandAck_ResponseSubscription struct {
	*rclgo.Subscription
}

// CommandAck_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a CommandAck_ResponseSubscription.
type CommandAck_ResponseSubscriptionCallback func(msg *CommandAck_Response, info *rclgo.MessageInfo, err error)

// NewCommandAck_ResponseSubscription creates and returns a new subscription for the
// CommandAck_Response
func NewCommandAck_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback CommandAck_ResponseSubscriptionCallback) (*CommandAck_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg CommandAck_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, CommandAck_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &CommandAck_ResponseSubscription{sub}, nil
}

func (s *CommandAck_ResponseSubscription) TakeMessage(out *CommandAck_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneCommandAck_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneCommandAck_ResponseSlice(dst, src []CommandAck_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var CommandAck_ResponseTypeSupport types.MessageTypeSupport = _CommandAck_ResponseTypeSupport{}

type _CommandAck_ResponseTypeSupport struct{}

func (t _CommandAck_ResponseTypeSupport) New() types.Message {
	return NewCommandAck_Response()
}

func (t _CommandAck_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__CommandAck_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__CommandAck_Response__create())
}

func (t _CommandAck_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__CommandAck_Response__destroy((*C.mavros_msgs__srv__CommandAck_Response)(pointer_to_free))
}

func (t _CommandAck_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*CommandAck_Response)
	mem := (*C.mavros_msgs__srv__CommandAck_Response)(dst)
	mem.success = C.bool(m.Success)
	mem.result = C.uint8_t(m.Result)
}

func (t _CommandAck_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*CommandAck_Response)
	mem := (*C.mavros_msgs__srv__CommandAck_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	m.Result = uint8(mem.result)
}

func (t _CommandAck_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__CommandAck_Response())
}

type CCommandAck_Response = C.mavros_msgs__srv__CommandAck_Response
type CCommandAck_Response__Sequence = C.mavros_msgs__srv__CommandAck_Response__Sequence

func CommandAck_Response__Sequence_to_Go(goSlice *[]CommandAck_Response, cSlice CCommandAck_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]CommandAck_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		CommandAck_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func CommandAck_Response__Sequence_to_C(cSlice *CCommandAck_Response__Sequence, goSlice []CommandAck_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__CommandAck_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__CommandAck_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		CommandAck_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func CommandAck_Response__Array_to_Go(goSlice []CommandAck_Response, cSlice []CCommandAck_Response) {
	for i := 0; i < len(cSlice); i++ {
		CommandAck_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func CommandAck_Response__Array_to_C(cSlice []CCommandAck_Response, goSlice []CommandAck_Response) {
	for i := 0; i < len(goSlice); i++ {
		CommandAck_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
