// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <mavros_msgs/srv/command_int.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("mavros_msgs/CommandInt", CommandIntTypeSupport)
	typemap.RegisterService("mavros_msgs/srv/CommandInt", CommandIntTypeSupport)
}

type _CommandIntTypeSupport struct {}

func (s _CommandIntTypeSupport) Request() types.MessageTypeSupport {
	return CommandInt_RequestTypeSupport
}

func (s _CommandIntTypeSupport) Response() types.MessageTypeSupport {
	return CommandInt_ResponseTypeSupport
}

func (s _CommandIntTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__mavros_msgs__srv__CommandInt())
}

// Modifying this variable is undefined behavior.
var CommandIntTypeSupport types.ServiceTypeSupport = _CommandIntTypeSupport{}

// CommandIntClient wraps rclgo.Client to provide type safe helper
// functions
type CommandIntClient struct {
	*rclgo.Client
}

// NewCommandIntClient creates and returns a new client for the
// CommandInt
func NewCommandIntClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*CommandIntClient, error) {
	client, err := node.NewClient(serviceName, CommandIntTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &CommandIntClient{client}, nil
}

func (s *CommandIntClient) Send(ctx context.Context, req *CommandInt_Request) (*CommandInt_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*CommandInt_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type CommandIntServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s CommandIntServiceResponseSender) SendResponse(resp *CommandInt_Response) error {
	return s.sender.SendResponse(resp)
}

type CommandIntServiceRequestHandler func(*rclgo.ServiceInfo, *CommandInt_Request, CommandIntServiceResponseSender)

// CommandIntService wraps rclgo.Service to provide type safe helper
// functions
type CommandIntService struct {
	*rclgo.Service
}

// NewCommandIntService creates and returns a new service for the
// CommandInt
func NewCommandIntService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler CommandIntServiceRequestHandler) (*CommandIntService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*CommandInt_Request)
		responseSender := CommandIntServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, CommandIntTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &CommandIntService{service}, nil
}