// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/endpoint_add.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/EndpointAdd_Response", EndpointAdd_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/EndpointAdd_Response", EndpointAdd_ResponseTypeSupport)
}

type EndpointAdd_Response struct {
	Successful bool `yaml:"successful"`// true if endpoint added and opened
	Reason string `yaml:"reason"`// returns error description if open fails
	Id uint32 `yaml:"id"`// ID of new endpoint, should be > 0 if endpoint created
}

// NewEndpointAdd_Response creates a new EndpointAdd_Response with default values.
func NewEndpointAdd_Response() *EndpointAdd_Response {
	self := EndpointAdd_Response{}
	self.SetDefaults()
	return &self
}

func (t *EndpointAdd_Response) Clone() *EndpointAdd_Response {
	c := &EndpointAdd_Response{}
	c.Successful = t.Successful
	c.Reason = t.Reason
	c.Id = t.Id
	return c
}

func (t *EndpointAdd_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *EndpointAdd_Response) SetDefaults() {
	t.Successful = false
	t.Reason = ""
	t.Id = 0
}

func (t *EndpointAdd_Response) GetTypeSupport() types.MessageTypeSupport {
	return EndpointAdd_ResponseTypeSupport
}

// EndpointAdd_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type EndpointAdd_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewEndpointAdd_ResponsePublisher creates and returns a new publisher for the
// EndpointAdd_Response
func NewEndpointAdd_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*EndpointAdd_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, EndpointAdd_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &EndpointAdd_ResponsePublisher{pub}, nil
}

func (p *EndpointAdd_ResponsePublisher) Publish(msg *EndpointAdd_Response) error {
	return p.Publisher.Publish(msg)
}

// EndpointAdd_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type EndpointAdd_ResponseSubscription struct {
	*rclgo.Subscription
}

// EndpointAdd_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a EndpointAdd_ResponseSubscription.
type EndpointAdd_ResponseSubscriptionCallback func(msg *EndpointAdd_Response, info *rclgo.MessageInfo, err error)

// NewEndpointAdd_ResponseSubscription creates and returns a new subscription for the
// EndpointAdd_Response
func NewEndpointAdd_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback EndpointAdd_ResponseSubscriptionCallback) (*EndpointAdd_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg EndpointAdd_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, EndpointAdd_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &EndpointAdd_ResponseSubscription{sub}, nil
}

func (s *EndpointAdd_ResponseSubscription) TakeMessage(out *EndpointAdd_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneEndpointAdd_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneEndpointAdd_ResponseSlice(dst, src []EndpointAdd_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var EndpointAdd_ResponseTypeSupport types.MessageTypeSupport = _EndpointAdd_ResponseTypeSupport{}

type _EndpointAdd_ResponseTypeSupport struct{}

func (t _EndpointAdd_ResponseTypeSupport) New() types.Message {
	return NewEndpointAdd_Response()
}

func (t _EndpointAdd_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__EndpointAdd_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__EndpointAdd_Response__create())
}

func (t _EndpointAdd_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__EndpointAdd_Response__destroy((*C.mavros_msgs__srv__EndpointAdd_Response)(pointer_to_free))
}

func (t _EndpointAdd_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*EndpointAdd_Response)
	mem := (*C.mavros_msgs__srv__EndpointAdd_Response)(dst)
	mem.successful = C.bool(m.Successful)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.reason), m.Reason)
	mem.id = C.uint32_t(m.Id)
}

func (t _EndpointAdd_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*EndpointAdd_Response)
	mem := (*C.mavros_msgs__srv__EndpointAdd_Response)(ros2_message_buffer)
	m.Successful = bool(mem.successful)
	primitives.StringAsGoStruct(&m.Reason, unsafe.Pointer(&mem.reason))
	m.Id = uint32(mem.id)
}

func (t _EndpointAdd_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__EndpointAdd_Response())
}

type CEndpointAdd_Response = C.mavros_msgs__srv__EndpointAdd_Response
type CEndpointAdd_Response__Sequence = C.mavros_msgs__srv__EndpointAdd_Response__Sequence

func EndpointAdd_Response__Sequence_to_Go(goSlice *[]EndpointAdd_Response, cSlice CEndpointAdd_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]EndpointAdd_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		EndpointAdd_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func EndpointAdd_Response__Sequence_to_C(cSlice *CEndpointAdd_Response__Sequence, goSlice []EndpointAdd_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__EndpointAdd_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__EndpointAdd_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		EndpointAdd_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func EndpointAdd_Response__Array_to_Go(goSlice []EndpointAdd_Response, cSlice []CEndpointAdd_Response) {
	for i := 0; i < len(cSlice); i++ {
		EndpointAdd_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func EndpointAdd_Response__Array_to_C(cSlice []CEndpointAdd_Response, goSlice []EndpointAdd_Response) {
	for i := 0; i < len(goSlice); i++ {
		EndpointAdd_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
