// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/file_rename.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/FileRename_Response", FileRename_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/FileRename_Response", FileRename_ResponseTypeSupport)
}

type FileRename_Response struct {
	Success bool `yaml:"success"`
	RErrno int32 `yaml:"r_errno"`
}

// NewFileRename_Response creates a new FileRename_Response with default values.
func NewFileRename_Response() *FileRename_Response {
	self := FileRename_Response{}
	self.SetDefaults()
	return &self
}

func (t *FileRename_Response) Clone() *FileRename_Response {
	c := &FileRename_Response{}
	c.Success = t.Success
	c.RErrno = t.RErrno
	return c
}

func (t *FileRename_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *FileRename_Response) SetDefaults() {
	t.Success = false
	t.RErrno = 0
}

func (t *FileRename_Response) GetTypeSupport() types.MessageTypeSupport {
	return FileRename_ResponseTypeSupport
}

// FileRename_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type FileRename_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewFileRename_ResponsePublisher creates and returns a new publisher for the
// FileRename_Response
func NewFileRename_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*FileRename_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, FileRename_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileRename_ResponsePublisher{pub}, nil
}

func (p *FileRename_ResponsePublisher) Publish(msg *FileRename_Response) error {
	return p.Publisher.Publish(msg)
}

// FileRename_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type FileRename_ResponseSubscription struct {
	*rclgo.Subscription
}

// FileRename_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a FileRename_ResponseSubscription.
type FileRename_ResponseSubscriptionCallback func(msg *FileRename_Response, info *rclgo.MessageInfo, err error)

// NewFileRename_ResponseSubscription creates and returns a new subscription for the
// FileRename_Response
func NewFileRename_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback FileRename_ResponseSubscriptionCallback) (*FileRename_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg FileRename_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, FileRename_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FileRename_ResponseSubscription{sub}, nil
}

func (s *FileRename_ResponseSubscription) TakeMessage(out *FileRename_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFileRename_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFileRename_ResponseSlice(dst, src []FileRename_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FileRename_ResponseTypeSupport types.MessageTypeSupport = _FileRename_ResponseTypeSupport{}

type _FileRename_ResponseTypeSupport struct{}

func (t _FileRename_ResponseTypeSupport) New() types.Message {
	return NewFileRename_Response()
}

func (t _FileRename_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__FileRename_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__FileRename_Response__create())
}

func (t _FileRename_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__FileRename_Response__destroy((*C.mavros_msgs__srv__FileRename_Response)(pointer_to_free))
}

func (t _FileRename_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FileRename_Response)
	mem := (*C.mavros_msgs__srv__FileRename_Response)(dst)
	mem.success = C.bool(m.Success)
	mem.r_errno = C.int32_t(m.RErrno)
}

func (t _FileRename_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FileRename_Response)
	mem := (*C.mavros_msgs__srv__FileRename_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	m.RErrno = int32(mem.r_errno)
}

func (t _FileRename_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__FileRename_Response())
}

type CFileRename_Response = C.mavros_msgs__srv__FileRename_Response
type CFileRename_Response__Sequence = C.mavros_msgs__srv__FileRename_Response__Sequence

func FileRename_Response__Sequence_to_Go(goSlice *[]FileRename_Response, cSlice CFileRename_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FileRename_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FileRename_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func FileRename_Response__Sequence_to_C(cSlice *CFileRename_Response__Sequence, goSlice []FileRename_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__FileRename_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__FileRename_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FileRename_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func FileRename_Response__Array_to_Go(goSlice []FileRename_Response, cSlice []CFileRename_Response) {
	for i := 0; i < len(cSlice); i++ {
		FileRename_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FileRename_Response__Array_to_C(cSlice []CFileRename_Response, goSlice []FileRename_Response) {
	for i := 0; i < len(goSlice); i++ {
		FileRename_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
