// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/file_checksum.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/FileChecksum_Response", FileChecksum_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/FileChecksum_Response", FileChecksum_ResponseTypeSupport)
}

type FileChecksum_Response struct {
	Crc32 uint32 `yaml:"crc32"`
	Success bool `yaml:"success"`
	RErrno int32 `yaml:"r_errno"`
}

// NewFileChecksum_Response creates a new FileChecksum_Response with default values.
func NewFileChecksum_Response() *FileChecksum_Response {
	self := FileChecksum_Response{}
	self.SetDefaults()
	return &self
}

func (t *FileChecksum_Response) Clone() *FileChecksum_Response {
	c := &FileChecksum_Response{}
	c.Crc32 = t.Crc32
	c.Success = t.Success
	c.RErrno = t.RErrno
	return c
}

func (t *FileChecksum_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *FileChecksum_Response) SetDefaults() {
	t.Crc32 = 0
	t.Success = false
	t.RErrno = 0
}

func (t *FileChecksum_Response) GetTypeSupport() types.MessageTypeSupport {
	return FileChecksum_ResponseTypeSupport
}

// FileChecksum_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type FileChecksum_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewFileChecksum_ResponsePublisher creates and returns a new publisher for the
// FileChecksum_Response
func NewFileChecksum_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*FileChecksum_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, FileChecksum_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileChecksum_ResponsePublisher{pub}, nil
}

func (p *FileChecksum_ResponsePublisher) Publish(msg *FileChecksum_Response) error {
	return p.Publisher.Publish(msg)
}

// FileChecksum_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type FileChecksum_ResponseSubscription struct {
	*rclgo.Subscription
}

// FileChecksum_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a FileChecksum_ResponseSubscription.
type FileChecksum_ResponseSubscriptionCallback func(msg *FileChecksum_Response, info *rclgo.MessageInfo, err error)

// NewFileChecksum_ResponseSubscription creates and returns a new subscription for the
// FileChecksum_Response
func NewFileChecksum_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback FileChecksum_ResponseSubscriptionCallback) (*FileChecksum_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg FileChecksum_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, FileChecksum_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FileChecksum_ResponseSubscription{sub}, nil
}

func (s *FileChecksum_ResponseSubscription) TakeMessage(out *FileChecksum_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFileChecksum_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFileChecksum_ResponseSlice(dst, src []FileChecksum_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FileChecksum_ResponseTypeSupport types.MessageTypeSupport = _FileChecksum_ResponseTypeSupport{}

type _FileChecksum_ResponseTypeSupport struct{}

func (t _FileChecksum_ResponseTypeSupport) New() types.Message {
	return NewFileChecksum_Response()
}

func (t _FileChecksum_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__FileChecksum_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__FileChecksum_Response__create())
}

func (t _FileChecksum_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__FileChecksum_Response__destroy((*C.mavros_msgs__srv__FileChecksum_Response)(pointer_to_free))
}

func (t _FileChecksum_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FileChecksum_Response)
	mem := (*C.mavros_msgs__srv__FileChecksum_Response)(dst)
	mem.crc32 = C.uint32_t(m.Crc32)
	mem.success = C.bool(m.Success)
	mem.r_errno = C.int32_t(m.RErrno)
}

func (t _FileChecksum_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FileChecksum_Response)
	mem := (*C.mavros_msgs__srv__FileChecksum_Response)(ros2_message_buffer)
	m.Crc32 = uint32(mem.crc32)
	m.Success = bool(mem.success)
	m.RErrno = int32(mem.r_errno)
}

func (t _FileChecksum_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__FileChecksum_Response())
}

type CFileChecksum_Response = C.mavros_msgs__srv__FileChecksum_Response
type CFileChecksum_Response__Sequence = C.mavros_msgs__srv__FileChecksum_Response__Sequence

func FileChecksum_Response__Sequence_to_Go(goSlice *[]FileChecksum_Response, cSlice CFileChecksum_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FileChecksum_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FileChecksum_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func FileChecksum_Response__Sequence_to_C(cSlice *CFileChecksum_Response__Sequence, goSlice []FileChecksum_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__FileChecksum_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__FileChecksum_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FileChecksum_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func FileChecksum_Response__Array_to_Go(goSlice []FileChecksum_Response, cSlice []CFileChecksum_Response) {
	for i := 0; i < len(cSlice); i++ {
		FileChecksum_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FileChecksum_Response__Array_to_C(cSlice []CFileChecksum_Response, goSlice []FileChecksum_Response) {
	for i := 0; i < len(goSlice); i++ {
		FileChecksum_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
