// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <mavros_msgs/srv/file_checksum.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("mavros_msgs/FileChecksum", FileChecksumTypeSupport)
	typemap.RegisterService("mavros_msgs/srv/FileChecksum", FileChecksumTypeSupport)
}

type _FileChecksumTypeSupport struct {}

func (s _FileChecksumTypeSupport) Request() types.MessageTypeSupport {
	return FileChecksum_RequestTypeSupport
}

func (s _FileChecksumTypeSupport) Response() types.MessageTypeSupport {
	return FileChecksum_ResponseTypeSupport
}

func (s _FileChecksumTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__mavros_msgs__srv__FileChecksum())
}

// Modifying this variable is undefined behavior.
var FileChecksumTypeSupport types.ServiceTypeSupport = _FileChecksumTypeSupport{}

// FileChecksumClient wraps rclgo.Client to provide type safe helper
// functions
type FileChecksumClient struct {
	*rclgo.Client
}

// NewFileChecksumClient creates and returns a new client for the
// FileChecksum
func NewFileChecksumClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*FileChecksumClient, error) {
	client, err := node.NewClient(serviceName, FileChecksumTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileChecksumClient{client}, nil
}

func (s *FileChecksumClient) Send(ctx context.Context, req *FileChecksum_Request) (*FileChecksum_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FileChecksum_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FileChecksumServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s FileChecksumServiceResponseSender) SendResponse(resp *FileChecksum_Response) error {
	return s.sender.SendResponse(resp)
}

type FileChecksumServiceRequestHandler func(*rclgo.ServiceInfo, *FileChecksum_Request, FileChecksumServiceResponseSender)

// FileChecksumService wraps rclgo.Service to provide type safe helper
// functions
type FileChecksumService struct {
	*rclgo.Service
}

// NewFileChecksumService creates and returns a new service for the
// FileChecksum
func NewFileChecksumService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler FileChecksumServiceRequestHandler) (*FileChecksumService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*FileChecksum_Request)
		responseSender := FileChecksumServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FileChecksumTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FileChecksumService{service}, nil
}