// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/file_truncate.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/FileTruncate_Request", FileTruncate_RequestTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/FileTruncate_Request", FileTruncate_RequestTypeSupport)
}

type FileTruncate_Request struct {
	FilePath string `yaml:"file_path"`
	Length uint64 `yaml:"length"`
}

// NewFileTruncate_Request creates a new FileTruncate_Request with default values.
func NewFileTruncate_Request() *FileTruncate_Request {
	self := FileTruncate_Request{}
	self.SetDefaults()
	return &self
}

func (t *FileTruncate_Request) Clone() *FileTruncate_Request {
	c := &FileTruncate_Request{}
	c.FilePath = t.FilePath
	c.Length = t.Length
	return c
}

func (t *FileTruncate_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *FileTruncate_Request) SetDefaults() {
	t.FilePath = ""
	t.Length = 0
}

func (t *FileTruncate_Request) GetTypeSupport() types.MessageTypeSupport {
	return FileTruncate_RequestTypeSupport
}

// FileTruncate_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type FileTruncate_RequestPublisher struct {
	*rclgo.Publisher
}

// NewFileTruncate_RequestPublisher creates and returns a new publisher for the
// FileTruncate_Request
func NewFileTruncate_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*FileTruncate_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, FileTruncate_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FileTruncate_RequestPublisher{pub}, nil
}

func (p *FileTruncate_RequestPublisher) Publish(msg *FileTruncate_Request) error {
	return p.Publisher.Publish(msg)
}

// FileTruncate_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type FileTruncate_RequestSubscription struct {
	*rclgo.Subscription
}

// FileTruncate_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a FileTruncate_RequestSubscription.
type FileTruncate_RequestSubscriptionCallback func(msg *FileTruncate_Request, info *rclgo.MessageInfo, err error)

// NewFileTruncate_RequestSubscription creates and returns a new subscription for the
// FileTruncate_Request
func NewFileTruncate_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback FileTruncate_RequestSubscriptionCallback) (*FileTruncate_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg FileTruncate_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, FileTruncate_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FileTruncate_RequestSubscription{sub}, nil
}

func (s *FileTruncate_RequestSubscription) TakeMessage(out *FileTruncate_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFileTruncate_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFileTruncate_RequestSlice(dst, src []FileTruncate_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FileTruncate_RequestTypeSupport types.MessageTypeSupport = _FileTruncate_RequestTypeSupport{}

type _FileTruncate_RequestTypeSupport struct{}

func (t _FileTruncate_RequestTypeSupport) New() types.Message {
	return NewFileTruncate_Request()
}

func (t _FileTruncate_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__FileTruncate_Request
	return (unsafe.Pointer)(C.mavros_msgs__srv__FileTruncate_Request__create())
}

func (t _FileTruncate_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__FileTruncate_Request__destroy((*C.mavros_msgs__srv__FileTruncate_Request)(pointer_to_free))
}

func (t _FileTruncate_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FileTruncate_Request)
	mem := (*C.mavros_msgs__srv__FileTruncate_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.file_path), m.FilePath)
	mem.length = C.uint64_t(m.Length)
}

func (t _FileTruncate_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FileTruncate_Request)
	mem := (*C.mavros_msgs__srv__FileTruncate_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.FilePath, unsafe.Pointer(&mem.file_path))
	m.Length = uint64(mem.length)
}

func (t _FileTruncate_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__FileTruncate_Request())
}

type CFileTruncate_Request = C.mavros_msgs__srv__FileTruncate_Request
type CFileTruncate_Request__Sequence = C.mavros_msgs__srv__FileTruncate_Request__Sequence

func FileTruncate_Request__Sequence_to_Go(goSlice *[]FileTruncate_Request, cSlice CFileTruncate_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FileTruncate_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FileTruncate_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func FileTruncate_Request__Sequence_to_C(cSlice *CFileTruncate_Request__Sequence, goSlice []FileTruncate_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__FileTruncate_Request)(C.malloc(C.sizeof_struct_mavros_msgs__srv__FileTruncate_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FileTruncate_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func FileTruncate_Request__Array_to_Go(goSlice []FileTruncate_Request, cSlice []CFileTruncate_Request) {
	for i := 0; i < len(cSlice); i++ {
		FileTruncate_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FileTruncate_Request__Array_to_C(cSlice []CFileTruncate_Request, goSlice []FileTruncate_Request) {
	for i := 0; i < len(goSlice); i++ {
		FileTruncate_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
