// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <mavros_msgs/srv/gimbal_manager_camera_track.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("mavros_msgs/GimbalManagerCameraTrack", GimbalManagerCameraTrackTypeSupport)
	typemap.RegisterService("mavros_msgs/srv/GimbalManagerCameraTrack", GimbalManagerCameraTrackTypeSupport)
}

type _GimbalManagerCameraTrackTypeSupport struct {}

func (s _GimbalManagerCameraTrackTypeSupport) Request() types.MessageTypeSupport {
	return GimbalManagerCameraTrack_RequestTypeSupport
}

func (s _GimbalManagerCameraTrackTypeSupport) Response() types.MessageTypeSupport {
	return GimbalManagerCameraTrack_ResponseTypeSupport
}

func (s _GimbalManagerCameraTrackTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__mavros_msgs__srv__GimbalManagerCameraTrack())
}

// Modifying this variable is undefined behavior.
var GimbalManagerCameraTrackTypeSupport types.ServiceTypeSupport = _GimbalManagerCameraTrackTypeSupport{}

// GimbalManagerCameraTrackClient wraps rclgo.Client to provide type safe helper
// functions
type GimbalManagerCameraTrackClient struct {
	*rclgo.Client
}

// NewGimbalManagerCameraTrackClient creates and returns a new client for the
// GimbalManagerCameraTrack
func NewGimbalManagerCameraTrackClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GimbalManagerCameraTrackClient, error) {
	client, err := node.NewClient(serviceName, GimbalManagerCameraTrackTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GimbalManagerCameraTrackClient{client}, nil
}

func (s *GimbalManagerCameraTrackClient) Send(ctx context.Context, req *GimbalManagerCameraTrack_Request) (*GimbalManagerCameraTrack_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GimbalManagerCameraTrack_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GimbalManagerCameraTrackServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GimbalManagerCameraTrackServiceResponseSender) SendResponse(resp *GimbalManagerCameraTrack_Response) error {
	return s.sender.SendResponse(resp)
}

type GimbalManagerCameraTrackServiceRequestHandler func(*rclgo.ServiceInfo, *GimbalManagerCameraTrack_Request, GimbalManagerCameraTrackServiceResponseSender)

// GimbalManagerCameraTrackService wraps rclgo.Service to provide type safe helper
// functions
type GimbalManagerCameraTrackService struct {
	*rclgo.Service
}

// NewGimbalManagerCameraTrackService creates and returns a new service for the
// GimbalManagerCameraTrack
func NewGimbalManagerCameraTrackService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GimbalManagerCameraTrackServiceRequestHandler) (*GimbalManagerCameraTrackService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GimbalManagerCameraTrack_Request)
		responseSender := GimbalManagerCameraTrackServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GimbalManagerCameraTrackTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GimbalManagerCameraTrackService{service}, nil
}