// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/gimbal_manager_pitchyaw.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/GimbalManagerPitchyaw_Response", GimbalManagerPitchyaw_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/GimbalManagerPitchyaw_Response", GimbalManagerPitchyaw_ResponseTypeSupport)
}

type GimbalManagerPitchyaw_Response struct {
	Success bool `yaml:"success"`
	Result uint8 `yaml:"result"`// raw result returned by COMMAND_ACK
}

// NewGimbalManagerPitchyaw_Response creates a new GimbalManagerPitchyaw_Response with default values.
func NewGimbalManagerPitchyaw_Response() *GimbalManagerPitchyaw_Response {
	self := GimbalManagerPitchyaw_Response{}
	self.SetDefaults()
	return &self
}

func (t *GimbalManagerPitchyaw_Response) Clone() *GimbalManagerPitchyaw_Response {
	c := &GimbalManagerPitchyaw_Response{}
	c.Success = t.Success
	c.Result = t.Result
	return c
}

func (t *GimbalManagerPitchyaw_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GimbalManagerPitchyaw_Response) SetDefaults() {
	t.Success = false
	t.Result = 0
}

func (t *GimbalManagerPitchyaw_Response) GetTypeSupport() types.MessageTypeSupport {
	return GimbalManagerPitchyaw_ResponseTypeSupport
}

// GimbalManagerPitchyaw_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GimbalManagerPitchyaw_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGimbalManagerPitchyaw_ResponsePublisher creates and returns a new publisher for the
// GimbalManagerPitchyaw_Response
func NewGimbalManagerPitchyaw_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GimbalManagerPitchyaw_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GimbalManagerPitchyaw_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GimbalManagerPitchyaw_ResponsePublisher{pub}, nil
}

func (p *GimbalManagerPitchyaw_ResponsePublisher) Publish(msg *GimbalManagerPitchyaw_Response) error {
	return p.Publisher.Publish(msg)
}

// GimbalManagerPitchyaw_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GimbalManagerPitchyaw_ResponseSubscription struct {
	*rclgo.Subscription
}

// GimbalManagerPitchyaw_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GimbalManagerPitchyaw_ResponseSubscription.
type GimbalManagerPitchyaw_ResponseSubscriptionCallback func(msg *GimbalManagerPitchyaw_Response, info *rclgo.MessageInfo, err error)

// NewGimbalManagerPitchyaw_ResponseSubscription creates and returns a new subscription for the
// GimbalManagerPitchyaw_Response
func NewGimbalManagerPitchyaw_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GimbalManagerPitchyaw_ResponseSubscriptionCallback) (*GimbalManagerPitchyaw_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GimbalManagerPitchyaw_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GimbalManagerPitchyaw_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GimbalManagerPitchyaw_ResponseSubscription{sub}, nil
}

func (s *GimbalManagerPitchyaw_ResponseSubscription) TakeMessage(out *GimbalManagerPitchyaw_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGimbalManagerPitchyaw_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGimbalManagerPitchyaw_ResponseSlice(dst, src []GimbalManagerPitchyaw_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GimbalManagerPitchyaw_ResponseTypeSupport types.MessageTypeSupport = _GimbalManagerPitchyaw_ResponseTypeSupport{}

type _GimbalManagerPitchyaw_ResponseTypeSupport struct{}

func (t _GimbalManagerPitchyaw_ResponseTypeSupport) New() types.Message {
	return NewGimbalManagerPitchyaw_Response()
}

func (t _GimbalManagerPitchyaw_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__GimbalManagerPitchyaw_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__GimbalManagerPitchyaw_Response__create())
}

func (t _GimbalManagerPitchyaw_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__GimbalManagerPitchyaw_Response__destroy((*C.mavros_msgs__srv__GimbalManagerPitchyaw_Response)(pointer_to_free))
}

func (t _GimbalManagerPitchyaw_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GimbalManagerPitchyaw_Response)
	mem := (*C.mavros_msgs__srv__GimbalManagerPitchyaw_Response)(dst)
	mem.success = C.bool(m.Success)
	mem.result = C.uint8_t(m.Result)
}

func (t _GimbalManagerPitchyaw_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GimbalManagerPitchyaw_Response)
	mem := (*C.mavros_msgs__srv__GimbalManagerPitchyaw_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	m.Result = uint8(mem.result)
}

func (t _GimbalManagerPitchyaw_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__GimbalManagerPitchyaw_Response())
}

type CGimbalManagerPitchyaw_Response = C.mavros_msgs__srv__GimbalManagerPitchyaw_Response
type CGimbalManagerPitchyaw_Response__Sequence = C.mavros_msgs__srv__GimbalManagerPitchyaw_Response__Sequence

func GimbalManagerPitchyaw_Response__Sequence_to_Go(goSlice *[]GimbalManagerPitchyaw_Response, cSlice CGimbalManagerPitchyaw_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GimbalManagerPitchyaw_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GimbalManagerPitchyaw_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GimbalManagerPitchyaw_Response__Sequence_to_C(cSlice *CGimbalManagerPitchyaw_Response__Sequence, goSlice []GimbalManagerPitchyaw_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__GimbalManagerPitchyaw_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__GimbalManagerPitchyaw_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GimbalManagerPitchyaw_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GimbalManagerPitchyaw_Response__Array_to_Go(goSlice []GimbalManagerPitchyaw_Response, cSlice []CGimbalManagerPitchyaw_Response) {
	for i := 0; i < len(cSlice); i++ {
		GimbalManagerPitchyaw_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GimbalManagerPitchyaw_Response__Array_to_C(cSlice []CGimbalManagerPitchyaw_Response, goSlice []GimbalManagerPitchyaw_Response) {
	for i := 0; i < len(goSlice); i++ {
		GimbalManagerPitchyaw_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
