// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/gimbal_manager_set_roi.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/GimbalManagerSetRoi_Response", GimbalManagerSetRoi_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/GimbalManagerSetRoi_Response", GimbalManagerSetRoi_ResponseTypeSupport)
}

type GimbalManagerSetRoi_Response struct {
	Success bool `yaml:"success"`
	Result uint8 `yaml:"result"`// raw result returned by COMMAND_ACK
}

// NewGimbalManagerSetRoi_Response creates a new GimbalManagerSetRoi_Response with default values.
func NewGimbalManagerSetRoi_Response() *GimbalManagerSetRoi_Response {
	self := GimbalManagerSetRoi_Response{}
	self.SetDefaults()
	return &self
}

func (t *GimbalManagerSetRoi_Response) Clone() *GimbalManagerSetRoi_Response {
	c := &GimbalManagerSetRoi_Response{}
	c.Success = t.Success
	c.Result = t.Result
	return c
}

func (t *GimbalManagerSetRoi_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GimbalManagerSetRoi_Response) SetDefaults() {
	t.Success = false
	t.Result = 0
}

func (t *GimbalManagerSetRoi_Response) GetTypeSupport() types.MessageTypeSupport {
	return GimbalManagerSetRoi_ResponseTypeSupport
}

// GimbalManagerSetRoi_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GimbalManagerSetRoi_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGimbalManagerSetRoi_ResponsePublisher creates and returns a new publisher for the
// GimbalManagerSetRoi_Response
func NewGimbalManagerSetRoi_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GimbalManagerSetRoi_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GimbalManagerSetRoi_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GimbalManagerSetRoi_ResponsePublisher{pub}, nil
}

func (p *GimbalManagerSetRoi_ResponsePublisher) Publish(msg *GimbalManagerSetRoi_Response) error {
	return p.Publisher.Publish(msg)
}

// GimbalManagerSetRoi_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GimbalManagerSetRoi_ResponseSubscription struct {
	*rclgo.Subscription
}

// GimbalManagerSetRoi_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GimbalManagerSetRoi_ResponseSubscription.
type GimbalManagerSetRoi_ResponseSubscriptionCallback func(msg *GimbalManagerSetRoi_Response, info *rclgo.MessageInfo, err error)

// NewGimbalManagerSetRoi_ResponseSubscription creates and returns a new subscription for the
// GimbalManagerSetRoi_Response
func NewGimbalManagerSetRoi_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GimbalManagerSetRoi_ResponseSubscriptionCallback) (*GimbalManagerSetRoi_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GimbalManagerSetRoi_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GimbalManagerSetRoi_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GimbalManagerSetRoi_ResponseSubscription{sub}, nil
}

func (s *GimbalManagerSetRoi_ResponseSubscription) TakeMessage(out *GimbalManagerSetRoi_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGimbalManagerSetRoi_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGimbalManagerSetRoi_ResponseSlice(dst, src []GimbalManagerSetRoi_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GimbalManagerSetRoi_ResponseTypeSupport types.MessageTypeSupport = _GimbalManagerSetRoi_ResponseTypeSupport{}

type _GimbalManagerSetRoi_ResponseTypeSupport struct{}

func (t _GimbalManagerSetRoi_ResponseTypeSupport) New() types.Message {
	return NewGimbalManagerSetRoi_Response()
}

func (t _GimbalManagerSetRoi_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__GimbalManagerSetRoi_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__GimbalManagerSetRoi_Response__create())
}

func (t _GimbalManagerSetRoi_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__GimbalManagerSetRoi_Response__destroy((*C.mavros_msgs__srv__GimbalManagerSetRoi_Response)(pointer_to_free))
}

func (t _GimbalManagerSetRoi_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GimbalManagerSetRoi_Response)
	mem := (*C.mavros_msgs__srv__GimbalManagerSetRoi_Response)(dst)
	mem.success = C.bool(m.Success)
	mem.result = C.uint8_t(m.Result)
}

func (t _GimbalManagerSetRoi_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GimbalManagerSetRoi_Response)
	mem := (*C.mavros_msgs__srv__GimbalManagerSetRoi_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	m.Result = uint8(mem.result)
}

func (t _GimbalManagerSetRoi_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__GimbalManagerSetRoi_Response())
}

type CGimbalManagerSetRoi_Response = C.mavros_msgs__srv__GimbalManagerSetRoi_Response
type CGimbalManagerSetRoi_Response__Sequence = C.mavros_msgs__srv__GimbalManagerSetRoi_Response__Sequence

func GimbalManagerSetRoi_Response__Sequence_to_Go(goSlice *[]GimbalManagerSetRoi_Response, cSlice CGimbalManagerSetRoi_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GimbalManagerSetRoi_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GimbalManagerSetRoi_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GimbalManagerSetRoi_Response__Sequence_to_C(cSlice *CGimbalManagerSetRoi_Response__Sequence, goSlice []GimbalManagerSetRoi_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__GimbalManagerSetRoi_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__GimbalManagerSetRoi_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GimbalManagerSetRoi_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GimbalManagerSetRoi_Response__Array_to_Go(goSlice []GimbalManagerSetRoi_Response, cSlice []CGimbalManagerSetRoi_Response) {
	for i := 0; i < len(cSlice); i++ {
		GimbalManagerSetRoi_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GimbalManagerSetRoi_Response__Array_to_C(cSlice []CGimbalManagerSetRoi_Response, goSlice []GimbalManagerSetRoi_Response) {
	for i := 0; i < len(goSlice); i++ {
		GimbalManagerSetRoi_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
