// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <mavros_msgs/srv/message_interval.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("mavros_msgs/MessageInterval", MessageIntervalTypeSupport)
	typemap.RegisterService("mavros_msgs/srv/MessageInterval", MessageIntervalTypeSupport)
}

type _MessageIntervalTypeSupport struct {}

func (s _MessageIntervalTypeSupport) Request() types.MessageTypeSupport {
	return MessageInterval_RequestTypeSupport
}

func (s _MessageIntervalTypeSupport) Response() types.MessageTypeSupport {
	return MessageInterval_ResponseTypeSupport
}

func (s _MessageIntervalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__mavros_msgs__srv__MessageInterval())
}

// Modifying this variable is undefined behavior.
var MessageIntervalTypeSupport types.ServiceTypeSupport = _MessageIntervalTypeSupport{}

// MessageIntervalClient wraps rclgo.Client to provide type safe helper
// functions
type MessageIntervalClient struct {
	*rclgo.Client
}

// NewMessageIntervalClient creates and returns a new client for the
// MessageInterval
func NewMessageIntervalClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*MessageIntervalClient, error) {
	client, err := node.NewClient(serviceName, MessageIntervalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MessageIntervalClient{client}, nil
}

func (s *MessageIntervalClient) Send(ctx context.Context, req *MessageInterval_Request) (*MessageInterval_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*MessageInterval_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type MessageIntervalServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s MessageIntervalServiceResponseSender) SendResponse(resp *MessageInterval_Response) error {
	return s.sender.SendResponse(resp)
}

type MessageIntervalServiceRequestHandler func(*rclgo.ServiceInfo, *MessageInterval_Request, MessageIntervalServiceResponseSender)

// MessageIntervalService wraps rclgo.Service to provide type safe helper
// functions
type MessageIntervalService struct {
	*rclgo.Service
}

// NewMessageIntervalService creates and returns a new service for the
// MessageInterval
func NewMessageIntervalService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler MessageIntervalServiceRequestHandler) (*MessageIntervalService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*MessageInterval_Request)
		responseSender := MessageIntervalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, MessageIntervalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &MessageIntervalService{service}, nil
}