// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <mavros_msgs/srv/set_mav_frame.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("mavros_msgs/SetMavFrame", SetMavFrameTypeSupport)
	typemap.RegisterService("mavros_msgs/srv/SetMavFrame", SetMavFrameTypeSupport)
}

type _SetMavFrameTypeSupport struct {}

func (s _SetMavFrameTypeSupport) Request() types.MessageTypeSupport {
	return SetMavFrame_RequestTypeSupport
}

func (s _SetMavFrameTypeSupport) Response() types.MessageTypeSupport {
	return SetMavFrame_ResponseTypeSupport
}

func (s _SetMavFrameTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__mavros_msgs__srv__SetMavFrame())
}

// Modifying this variable is undefined behavior.
var SetMavFrameTypeSupport types.ServiceTypeSupport = _SetMavFrameTypeSupport{}

// SetMavFrameClient wraps rclgo.Client to provide type safe helper
// functions
type SetMavFrameClient struct {
	*rclgo.Client
}

// NewSetMavFrameClient creates and returns a new client for the
// SetMavFrame
func NewSetMavFrameClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SetMavFrameClient, error) {
	client, err := node.NewClient(serviceName, SetMavFrameTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetMavFrameClient{client}, nil
}

func (s *SetMavFrameClient) Send(ctx context.Context, req *SetMavFrame_Request) (*SetMavFrame_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetMavFrame_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetMavFrameServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SetMavFrameServiceResponseSender) SendResponse(resp *SetMavFrame_Response) error {
	return s.sender.SendResponse(resp)
}

type SetMavFrameServiceRequestHandler func(*rclgo.ServiceInfo, *SetMavFrame_Request, SetMavFrameServiceResponseSender)

// SetMavFrameService wraps rclgo.Service to provide type safe helper
// functions
type SetMavFrameService struct {
	*rclgo.Service
}

// NewSetMavFrameService creates and returns a new service for the
// SetMavFrame
func NewSetMavFrameService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SetMavFrameServiceRequestHandler) (*SetMavFrameService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*SetMavFrame_Request)
		responseSender := SetMavFrameServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetMavFrameTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetMavFrameService{service}, nil
}