// Code generated by rclgo-gen. DO NOT EDIT.

package mavros_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	mavros_msgs_msg "test/msgs/mavros_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <mavros_msgs/srv/vehicle_info_get.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("mavros_msgs/VehicleInfoGet_Response", VehicleInfoGet_ResponseTypeSupport)
	typemap.RegisterMessage("mavros_msgs/srv/VehicleInfoGet_Response", VehicleInfoGet_ResponseTypeSupport)
}

type VehicleInfoGet_Response struct {
	Success bool `yaml:"success"`
	Vehicles []mavros_msgs_msg.VehicleInfo `yaml:"vehicles"`
}

// NewVehicleInfoGet_Response creates a new VehicleInfoGet_Response with default values.
func NewVehicleInfoGet_Response() *VehicleInfoGet_Response {
	self := VehicleInfoGet_Response{}
	self.SetDefaults()
	return &self
}

func (t *VehicleInfoGet_Response) Clone() *VehicleInfoGet_Response {
	c := &VehicleInfoGet_Response{}
	c.Success = t.Success
	if t.Vehicles != nil {
		c.Vehicles = make([]mavros_msgs_msg.VehicleInfo, len(t.Vehicles))
		mavros_msgs_msg.CloneVehicleInfoSlice(c.Vehicles, t.Vehicles)
	}
	return c
}

func (t *VehicleInfoGet_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *VehicleInfoGet_Response) SetDefaults() {
	t.Success = false
	t.Vehicles = nil
}

func (t *VehicleInfoGet_Response) GetTypeSupport() types.MessageTypeSupport {
	return VehicleInfoGet_ResponseTypeSupport
}

// VehicleInfoGet_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type VehicleInfoGet_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewVehicleInfoGet_ResponsePublisher creates and returns a new publisher for the
// VehicleInfoGet_Response
func NewVehicleInfoGet_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*VehicleInfoGet_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, VehicleInfoGet_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &VehicleInfoGet_ResponsePublisher{pub}, nil
}

func (p *VehicleInfoGet_ResponsePublisher) Publish(msg *VehicleInfoGet_Response) error {
	return p.Publisher.Publish(msg)
}

// VehicleInfoGet_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type VehicleInfoGet_ResponseSubscription struct {
	*rclgo.Subscription
}

// VehicleInfoGet_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a VehicleInfoGet_ResponseSubscription.
type VehicleInfoGet_ResponseSubscriptionCallback func(msg *VehicleInfoGet_Response, info *rclgo.MessageInfo, err error)

// NewVehicleInfoGet_ResponseSubscription creates and returns a new subscription for the
// VehicleInfoGet_Response
func NewVehicleInfoGet_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback VehicleInfoGet_ResponseSubscriptionCallback) (*VehicleInfoGet_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg VehicleInfoGet_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, VehicleInfoGet_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &VehicleInfoGet_ResponseSubscription{sub}, nil
}

func (s *VehicleInfoGet_ResponseSubscription) TakeMessage(out *VehicleInfoGet_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneVehicleInfoGet_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneVehicleInfoGet_ResponseSlice(dst, src []VehicleInfoGet_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var VehicleInfoGet_ResponseTypeSupport types.MessageTypeSupport = _VehicleInfoGet_ResponseTypeSupport{}

type _VehicleInfoGet_ResponseTypeSupport struct{}

func (t _VehicleInfoGet_ResponseTypeSupport) New() types.Message {
	return NewVehicleInfoGet_Response()
}

func (t _VehicleInfoGet_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.mavros_msgs__srv__VehicleInfoGet_Response
	return (unsafe.Pointer)(C.mavros_msgs__srv__VehicleInfoGet_Response__create())
}

func (t _VehicleInfoGet_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.mavros_msgs__srv__VehicleInfoGet_Response__destroy((*C.mavros_msgs__srv__VehicleInfoGet_Response)(pointer_to_free))
}

func (t _VehicleInfoGet_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*VehicleInfoGet_Response)
	mem := (*C.mavros_msgs__srv__VehicleInfoGet_Response)(dst)
	mem.success = C.bool(m.Success)
	mavros_msgs_msg.VehicleInfo__Sequence_to_C((*mavros_msgs_msg.CVehicleInfo__Sequence)(unsafe.Pointer(&mem.vehicles)), m.Vehicles)
}

func (t _VehicleInfoGet_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*VehicleInfoGet_Response)
	mem := (*C.mavros_msgs__srv__VehicleInfoGet_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	mavros_msgs_msg.VehicleInfo__Sequence_to_Go(&m.Vehicles, *(*mavros_msgs_msg.CVehicleInfo__Sequence)(unsafe.Pointer(&mem.vehicles)))
}

func (t _VehicleInfoGet_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__mavros_msgs__srv__VehicleInfoGet_Response())
}

type CVehicleInfoGet_Response = C.mavros_msgs__srv__VehicleInfoGet_Response
type CVehicleInfoGet_Response__Sequence = C.mavros_msgs__srv__VehicleInfoGet_Response__Sequence

func VehicleInfoGet_Response__Sequence_to_Go(goSlice *[]VehicleInfoGet_Response, cSlice CVehicleInfoGet_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]VehicleInfoGet_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		VehicleInfoGet_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func VehicleInfoGet_Response__Sequence_to_C(cSlice *CVehicleInfoGet_Response__Sequence, goSlice []VehicleInfoGet_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.mavros_msgs__srv__VehicleInfoGet_Response)(C.malloc(C.sizeof_struct_mavros_msgs__srv__VehicleInfoGet_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		VehicleInfoGet_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func VehicleInfoGet_Response__Array_to_Go(goSlice []VehicleInfoGet_Response, cSlice []CVehicleInfoGet_Response) {
	for i := 0; i < len(cSlice); i++ {
		VehicleInfoGet_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func VehicleInfoGet_Response__Array_to_C(cSlice []CVehicleInfoGet_Response, goSlice []VehicleInfoGet_Response) {
	for i := 0; i < len(goSlice); i++ {
		VehicleInfoGet_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
